# Exemplo de uso

Para usar o juscraper, rode algo assim:

In [1]:
import juscraper as jus

# cria um objeto datajud
datajud = jus.scraper('datajud', verbose=False)

/home/brunodcdo/Desktop/dev/2026/juscraper/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:

# lista os processos
processos = ['10092161720238260016', '00665754820248190000']
listagem = datajud.listar_processos(numero_processo=processos, mostrar_movs=True)

print(listagem.shape)
listagem.head(3)

Paginando api_publica_tjsp: 0 página [00:00, ? página/s]

Paginando api_publica_tjsp: 1 página [00:00,  2.95 página/s]

Paginando api_publica_tjsp: 1 página [00:00,  2.95 página/s]

Paginando api_publica_tjrj: 0 página [00:00, ? página/s]

Paginando api_publica_tjrj: 1 página [00:00,  4.92 página/s]

Paginando api_publica_tjrj: 1 página [00:00,  4.91 página/s]

(2, 14)

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,movimentos,id,nivelSigilo,orgaoJulgador,assuntos
0,"{'codigo': 241, 'nome': 'Petição Cível'}",10092161720238260016,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-08-14T23:45:57.652Z,JE,2025-10-28T12:09:22.593114816Z,20230426112734,"[{'complementosTabelados': [{'codigo': 2, 'val...",TJSP_JE_10092161720238260016,0,"{'codigo': 10608, 'nome': '02 VARA JUIZADO ESP...","[{'codigo': 8893, 'nome': 'Atos Processuais'}]"
1,"{'codigo': 202, 'nome': 'Agravo de Instrumento'}",00665754820248190000,"{'codigo': 8, 'nome': 'Outros'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJRJ,2025-08-13T10:35:41.805Z,G2,2025-10-03T17:41:02.246069489Z,20240816150706,"[{'complementosTabelados': [{'codigo': 4, 'val...",TJRJ_G2_00665754820248190000,0,"{'codigoMunicipioIBGE': 3304557, 'codigo': 291...","[{'codigo': 10499, 'nome': 'Programa de Comput..."

In [3]:
listagem = datajud.listar_processos(numero_processo=processos)
listagem

Paginando api_publica_tjsp: 0 página [00:00, ? página/s]

Paginando api_publica_tjsp: 1 página [00:00, 17.70 página/s]

Paginando api_publica_tjrj: 0 página [00:00, ? página/s]

Paginando api_publica_tjrj: 1 página [00:00,  1.06 página/s]

Paginando api_publica_tjrj: 1 página [00:00,  1.06 página/s]

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,id,nivelSigilo,orgaoJulgador,assuntos
0,"{'codigo': 241, 'nome': 'Petição Cível'}",10092161720238260016,"{'codigo': 3, 'nome': 'SAJ'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJSP,2025-08-14T23:45:57.652Z,JE,2025-10-28T12:09:22.593114816Z,20230426112734,TJSP_JE_10092161720238260016,0,"{'codigo': 10608, 'nome': '02 VARA JUIZADO ESP...","[{'codigo': 8893, 'nome': 'Atos Processuais'}]"
1,"{'codigo': 202, 'nome': 'Agravo de Instrumento'}",00665754820248190000,"{'codigo': 8, 'nome': 'Outros'}","{'codigo': 1, 'nome': 'Eletrônico'}",TJRJ,2025-08-13T10:35:41.805Z,G2,2025-10-03T17:41:02.246069489Z,20240816150706,TJRJ_G2_00665754820248190000,0,"{'codigoMunicipioIBGE': 3304557, 'codigo': 291...","[{'codigo': 10499, 'nome': 'Programa de Comput..."

In [4]:
listagem = datajud.listar_processos(classe = '282', tribunal = 'TJRJ', mostrar_movs=False, paginas=range(1, 16))

print(listagem.shape)
listagem.head(3)

Paginando api_publica_tjrj:   0%|          | 0/15 [00:00<?, ? página/s]

Paginando api_publica_tjrj:   7%|▋         | 1/15 [00:17<04:08, 17.73s/ página]

Paginando api_publica_tjrj:  13%|█▎        | 2/15 [00:44<05:00, 23.13s/ página]

Paginando api_publica_tjrj:  20%|██        | 3/15 [00:55<03:27, 17.33s/ página]

Paginando api_publica_tjrj:  27%|██▋       | 4/15 [01:16<03:29, 19.06s/ página]

Paginando api_publica_tjrj:  33%|███▎      | 5/15 [01:39<03:25, 20.53s/ página]

Paginando api_publica_tjrj:  40%|████      | 6/15 [01:49<02:32, 16.97s/ página]

Paginando api_publica_tjrj:  47%|████▋     | 7/15 [01:59<01:56, 14.57s/ página]

Paginando api_publica_tjrj:  53%|█████▎    | 8/15 [02:07<01:26, 12.30s/ página]

Paginando api_publica_tjrj:  60%|██████    | 9/15 [02:24<01:23, 13.85s/ página]

Paginando api_publica_tjrj:  67%|██████▋   | 10/15 [02:38<01:10, 14.10s/ página]

Paginando api_publica_tjrj:  73%|███████▎  | 11/15 [02:54<00:58, 14.61s/ página]

Paginando api_publica_tjrj:  80%|████████  | 12/15 [03:08<00:43, 14.45s/ página]

Paginando api_publica_tjrj:  87%|████████▋ | 13/15 [03:23<00:29, 14.65s/ página]

Paginando api_publica_tjrj:  93%|█████████▎| 14/15 [03:40<00:15, 15.14s/ página]

Paginando api_publica_tjrj: 100%|██████████| 15/15 [04:02<00:00, 17.34s/ página]

Paginando api_publica_tjrj: 100%|██████████| 15/15 [04:02<00:00, 16.18s/ página]

(15000, 13)

,classe,numeroProcesso,sistema,formato,tribunal,dataHoraUltimaAtualizacao,grau,@timestamp,dataAjuizamento,id,nivelSigilo,orgaoJulgador,assuntos
0,"{'codigo': 282, 'nome': 'Ação Penal de Competê...",00003298920088190078,"{'codigo': 8, 'nome': 'Outros'}","{'codigo': 2, 'nome': 'Físico'}",TJRJ,2023-08-15T08:01:14.384Z,G1,2025-06-15T21:21:53.344048218Z,2009-11-09T00:00:00.000Z,TJRJ_282_G1_11376_00003298920088190078,0,"{'codigoMunicipioIBGE': 3300233, 'codigo': 113...","[{'codigo': 3370, 'nome': 'Homicídio Simples'}]"
1,"{'codigo': 282, 'nome': 'Ação Penal de Competê...",00004880820038190078,"{'codigo': 8, 'nome': 'Outros'}","{'codigo': 2, 'nome': 'Físico'}",TJRJ,2023-08-31T03:10:45.783Z,G1,2025-06-15T22:43:25.312100568Z,2003-04-01T00:00:00.000Z,TJRJ_282_G1_11376_00004880820038190078,0,"{'codigoMunicipioIBGE': 3300233, 'codigo': 113...","[{'codigo': 3372, 'nome': 'Homicídio Qualifica..."
2,"{'codigo': 282, 'nome': 'Ação Penal de Competê...",00004890720148190078,"{'codigo': 8, 'nome': 'Outros'}","{'codigo': 2, 'nome': 'Físico'}",TJRJ,2023-08-13T18:25:12.385Z,G1,2025-06-15T20:41:34.872734077Z,2014-01-31T00:00:00.000Z,TJRJ_282_G1_11376_00004890720148190078,0,"{'codigoMunicipioIBGE': 3300233, 'codigo': 113...","[{'codigo': 3372, 'nome': 'Homicídio Qualifica..."

In [5]:
listagem = datajud.listar_processos(
    assuntos = [12503], 
    mostrar_movs=False, 
    tribunal = 'TJMG'
)

listagem.head(3)

Paginando api_publica_tjmg: 0 página [00:00, ? página/s]

HTTP Error calling Datajud API (https://api-publica.datajud.cnj.jus.br/api_publica_tjmg/_search): 504 Server Error: Gateway Time-out for url: https://api-publica.datajud.cnj.jus.br/api_publica_tjmg/_search

Response status: 504

Response content: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>NSX LB</center>
</body>
</html>

Failed to get API response for alias api_publica_tjmg, page 1.Stopping.

Paginando api_publica_tjmg: 0 página [01:00, ? página/s]

Empty DataFrame
Columns: []
Index: []