# TJAC - Tribunal de Justica do Acre

Scraper for the jurisprudence search (CJSG) of the Tribunal de Justica do Acre.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |
| cpopg   | No       |
| cposg   | No       |

## Basic search

In [1]:
import juscraper as jus

tjac = jus.scraper('tjac')

In [2]:
df = tjac.cjsg('dano moral', paginas=range(1, 3))
print(df.shape)
df.head(3)

Baixando CJSG TJAC: 100%|██████████| 2/2 [00:01<00:00,  1.48s/it]
Processando CJSG TJAC: 100%|██████████| 2/2 [00:00<00:00, 19.34it/s]

(40, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0712323-18.2025.8.01.0001,2502928,0,Apelação Cível / Alienação Fiduciária,Desª. Waldirene Cordeiro,Rio Branco,Segunda Câmara Cível,08/04/2026,08/04/2026,CIVIL. PROCESSO CIVIL. APELAÇÃO CÍVEL. BUSCA E...
1,0100293-66.2026.8.01.0000,2502948,0,Conflito de competência cível / Competência da...,Des. Júnior Alberto,Rio Branco,Segunda Câmara Cível,07/04/2026,08/04/2026,DIREITO PROCESSUAL CIVIL. CONFLITO NEGATIVO DE...
2,0721736-89.2024.8.01.0001,2502950,0,Apelação Cível / Tratamento médico-hospitalar,Desª. Waldirene Cordeiro,Rio Branco,Segunda Câmara Cível,07/04/2026,08/04/2026,CONSUMIDOR. PROCESSUAL CIVIL. DIREITO À SAÚDE....

## Available columns

In [3]:
df.columns.tolist()

['processo',
 'cd_acordao',
 'cd_foro',
 'classe_assunto',
 'relatora',
 'comarca',
 'orgao_julgador',
 'data_julgamento',
 'data_publicacao',
 'ementa']

## Preview ementa

In [4]:
print(df['ementa'].iloc[0][:300])

CIVIL. PROCESSO CIVIL. APELAÇÃO CÍVEL. BUSCA E APREENSÃO. ALIENAÇÃO FIDUCIÁRIA EM GARANTIA. INADIMPLEMENTO CONTRATUAL. NOTIFICAÇÃO EXTRAJUDICIAL. PURGAÇÃO DA MORA. PAGAMENTO INTEGRAL DA DÍVIDA. DECRETO-LEI Nº 911/69, ARTS. 2º, §2º, E 3º, §§1º E 2º. ALEGAÇÃO DE ABUSO DE DIREITO E VIOLAÇÃO À BOA-FÉ OB

## Using filters

You can filter by judgment date, publication date, decision type, and other fields.

In [5]:
df_filtered = tjac.cjsg(
    'direito',
    data_julgamento_inicio='01/01/2024',
    data_julgamento_fim='30/06/2024',
    paginas=1,
)
print(df_filtered.shape)
df_filtered.head(3)

Processando CJSG TJAC: 100%|██████████| 1/1 [00:00<00:00, 13.16it/s]

(20, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0006503-64.2022.8.01.0001,2471902,0,Apelação Criminal / Roubo Majorado,Desª. Denise Bonfim,Rio Branco,Câmara Criminal,27/06/2024,29/08/2024,PENAL. PROCESSUAL PENAL. APELAÇÕES CRIMINAIS D...
1,0802195-83.2021.8.01.0001,2469395,0,Apelação Criminal / Crimes de Tortura,Desª. Denise Bonfim,Rio Branco,Câmara Criminal,21/05/2024,09/07/2024,VV. APELAÇÃO CRIMINAL - LESÃO CORPORAL. TORTUR...
2,0006536-20.2023.8.01.0001,2469403,0,Apelação Criminal / Tráfico de Drogas e Condut...,Des. Francisco Djalma,Rio Branco,Câmara Criminal,27/06/2024,09/07/2024,DIREITO PENAL. PROCESSO PENAL. TRÁFICO DE DROG...

## Download and parse separately

You can also download the raw HTML files and parse them in a separate step.

In [6]:
import tempfile, os

tmp = tempfile.mkdtemp()
pasta = tjac.cjsg_download('direito', paginas=1, diretorio=tmp)
print('Downloaded to:', pasta)
print('Files:', os.listdir(pasta))

Downloaded to: C:\Users\jtrec\AppData\Local\Temp\tmpez3zkxep\cjsg\20260409100826
Files: ['cjsg_00001.html']

In [7]:
df_parsed = tjac.cjsg_parse(pasta)
print(df_parsed.shape)
df_parsed.head(3)

Processando CJSG TJAC: 100%|██████████| 1/1 [00:00<00:00, 24.95it/s]

(20, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0800015-29.2023.8.01.0000,2502957,0,Procedimento Investigatório Criminal (PIC-MP) ...,Des. Samoel Evangelista,Rio Branco,Tribunal Pleno Jurisdicional,08/04/2026,09/04/2026,DIREITO PENAL E PROCESSUAL PENAL. INQUÉRITO. C...
1,0000541-18.2022.8.01.0015,2502938,0,Apelação Criminal / Homicídio Qualificado,Des. Samoel Evangelista,Mâncio Lima,Câmara Criminal,09/04/2026,09/04/2026,DIREITO PENAL E PROCESSUAL PENAL. APELAÇÃO CRI...
2,0000445-09.2022.8.01.0013,2502940,0,Apelação Criminal / Homicídio Qualificado,Des. Samoel Evangelista,Feijó,Câmara Criminal,09/04/2026,09/04/2026,Direito Penal e Processual Penal. Apelação Cri...