# TJAL - Tribunal de Justica de Alagoas

Scraper for the jurisprudence search (CJSG) of the Tribunal de Justica de Alagoas.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |
| cpopg   | No       |
| cposg   | No       |

## Basic search

In [1]:
import juscraper as jus

tjal = jus.scraper('tjal')

In [2]:
df = tjal.cjsg('dano moral', paginas=range(1, 3))
print(df.shape)
df.head(3)

Baixando CJSG TJAL: 100%|██████████| 2/2 [00:01<00:00,  1.71s/it]
Processando CJSG TJAL: 100%|██████████| 2/2 [00:00<00:00, 22.77it/s]

(40, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0747976-88.2024.8.02.0001,807334,0,Apelação Cível / Inclusão Indevida em Cadastro...,Des. Otávio Leão Praxedes,Maceió,2ª Câmara Cível,30/03/2026,30/03/2026,DIREITO CIVIL E DO CONSUMIDOR. APELAÇÃO CÍVEL....
1,0743913-54.2023.8.02.0001,807323,0,Apelação Cível / Irredutibilidade de Vencimentos,Des. Otávio Leão Praxedes,Maceió,2ª Câmara Cível,30/03/2026,30/03/2026,DIREITO ADMINISTRATIVO E PROCESSUAL CIVIL. APE...
2,0746985-49.2023.8.02.0001,807329,0,Apelação Cível / Alteração de Coisa Comum,Des. Otávio Leão Praxedes,Maceió,2ª Câmara Cível,30/03/2026,30/03/2026,DIREITO ADMINISTRATIVO E TRIBUTÁRIO. APELAÇÃO ...

## Available columns

In [3]:
df.columns.tolist()

['processo',
 'cd_acordao',
 'cd_foro',
 'classe_assunto',
 'relatora',
 'comarca',
 'orgao_julgador',
 'data_julgamento',
 'data_publicacao',
 'ementa']

## Preview ementa

In [4]:
print(df['ementa'].iloc[0][:300])

DIREITO CIVIL E DO CONSUMIDOR. APELAÇÃO CÍVEL. SISTEMA DE INFORMAÇÕES DE CRÉDITO DO BANCO CENTRAL (SCR/SISBACEN). INCLUSÃO DE DADOS DE OPERAÇÃO DE CRÉDITO. NATUREZA INFORMATIVA DO CADASTRO. DISTINÇÃO EM RELAÇÃO AOS CADASTROS RESTRITIVOS DE CRÉDITO. AUSÊNCIA DE PROVA DE RECUSA DE CRÉDITO OU PREJUÍZO

## Using filters

You can filter by judgment date, publication date, decision type, and other fields.

In [5]:
df_filtered = tjal.cjsg(
    'direito',
    data_julgamento_inicio='01/01/2024',
    data_julgamento_fim='30/06/2024',
    paginas=1,
)
print(df_filtered.shape)
df_filtered.head(3)

Processando CJSG TJAL: 100%|██████████| 1/1 [00:00<00:00, 13.02it/s]

(20, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0806617-43.2022.8.02.0000,743582,0,Agravo de Instrumento / Auxílio-Doença Acident...,Des. Paulo Zacarias da Silva,Comarcar não Econtrada,3ª Câmara Cível,13/06/2024,16/10/2025,AGRAVO DE INSTRUMENTO. PROCESSUAL CIVIL. PREVI...
1,0700333-82.2021.8.02.0020,740034,0,Apelação Cível / Rescisão,Juiz Convocado Manoel Cavalcante de Lima Neto,Maravilha,1ª Câmara Cível,13/06/2024,08/10/2025,APELAÇÃO CÍVEL. DIREITO ADMINISTRATIVO E CONST...
2,0807502-91.2021.8.02.0000,676103,0,Ação Rescisória / Suspensão do Processo,Des. Tutmés Airan de Albuquerque Melo,Maceió,Seção Especializada Cível,01/04/2024,30/04/2025,em>DIREITO PROCESSUAL CIVIL. AÇÃO RESCISÓRIA. ...

## Download and parse separately

You can also download the raw HTML files and parse them in a separate step.

In [6]:
import tempfile, os

tmp = tempfile.mkdtemp()
pasta = tjal.cjsg_download('direito', paginas=1, diretorio=tmp)
print('Downloaded to:', pasta)
print('Files:', os.listdir(pasta))

Downloaded to: C:\Users\jtrec\AppData\Local\Temp\tmpth5xctlc\cjsg\20260409100830
Files: ['cjsg_00001.html']

In [7]:
df_parsed = tjal.cjsg_parse(pasta)
print(df_parsed.shape)
df_parsed.head(3)

Processando CJSG TJAL: 100%|██████████| 1/1 [00:00<00:00, 29.97it/s]

(20, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0701016-24.2024.8.02.0050,807619,0,Agravo Interno Criminal / Crimes de Trânsito,Presidente do Tribunal de Justiça de Alagoas,Porto Calvo,Tribunal Pleno,31/03/2026,31/03/2026,em>DIREITO PROCESSUAL CIVIL. AGRAVO INTERNO. R...
1,0808946-23.2025.8.02.0000,807620,0,Embargos de Declaração Criminal / Homicídio Qu...,Presidente do Tribunal de Justiça de Alagoas,Traipu,Tribunal Pleno,31/03/2026,31/03/2026,EMBARGOS DE DECLARAÇÃO EM MANDADO DE SEGURANÇA...
2,0701748-42.2023.8.02.0049,807617,0,Agravo Interno Cível / Tratamento da Própria S...,Presidente do Tribunal de Justiça de Alagoas,Penedo,Tribunal Pleno,31/03/2026,31/03/2026,em>DIREITO PROCESSUAL CIVIL. AGRAVO INTERNO. D...