# TJAM - Tribunal de Justica do Amazonas

Scraper for the jurisprudence search (CJSG) of the Tribunal de Justica do Amazonas.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |
| cpopg   | No       |
| cposg   | No       |

## Basic search

In [1]:
import juscraper as jus

tjam = jus.scraper('tjam')

In [2]:
df = tjam.cjsg('dano moral', paginas=range(1, 3))
print(df.shape)
df.head(3)

Baixando CJSG TJAM: 100%|██████████| 2/2 [00:01<00:00,  1.29s/it]
Processando CJSG TJAM: 100%|██████████| 2/2 [00:00<00:00, 38.67it/s]

(20, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0708349-62.2020.8.04.0001,3363939,0,Apelação Cível / Indenização por Dano Material,Délcio Luís Santos,Manaus,Segunda Câmara Cível,25/11/2024,18/09/2025,APELAÇÕES CÍVEIS. DIREITO CIVIL. DIREITO CONSU...
1,0515824-48.2023.8.04.0001,3363938,0,Apelação Cível / Limitação de Juros,Domingos Jorge Chalub Pereira,Manaus,Terceira Câmara Cível,29/07/2025,29/07/2025,DIREITO DO CONSUMIDOR E PROCESSUAL CIVIL – TAX...
2,0006912-88.2024.8.04.0000,3363937,0,Agravo Interno Cível / Cartão de Crédito,Socorro Guedes Moura,Manaus,Segunda Câmara Cível,01/06/2004,16/07/2025,DIREITO DO CONSUMIDOR. AGRAVO INTERNO. CONTRAT...

## Available columns

In [3]:
df.columns.tolist()

['processo',
 'cd_acordao',
 'cd_foro',
 'classe_assunto',
 'relatora',
 'comarca',
 'orgao_julgador',
 'data_julgamento',
 'data_publicacao',
 'ementa']

## Preview ementa

In [4]:
print(df['ementa'].iloc[0][:300])

APELAÇÕES CÍVEIS. DIREITO CIVIL. DIREITO CONSUMERISTA. PLANO DE SAÚDE. RECUSA DE ATENDIMENTO NA REDE CREDENCIADA. FALHA NA PRESTAÇÃO DO SERVIÇO. DANO MORAL ARBITRADO EM FAVOR DO MENOR AUTOR-APELANTE E DE SUA GENITORA. RECURSO DE APELAÇÃO MANEJADO APENAS PELO MENOR. MAJORAÇÃO. POSSIBILIDADE. PRIMEIRO

## Using filters

You can filter by judgment date, publication date, decision type, and other fields.

In [5]:
df_filtered = tjam.cjsg(
    'direito',
    data_julgamento_inicio='01/01/2024',
    data_julgamento_fim='30/06/2024',
    paginas=1,
)
print(df_filtered.shape)
df_filtered.head(3)

Processando CJSG TJAM: 100%|██████████| 1/1 [00:00<00:00, 42.78it/s]

(10, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,4000873-41.2023.8.04.0000,3320189,0,Agravo de Instrumento / Posse e Exercício,Cláudio César Ramalheira Roessing,Manaus,Primeira Câmara Cível,20/05/2024,31/07/2024,AGRAVO DE INSTRUMENTO. DEFERIMENTO DE TUTELA D...
1,0002831-96.2024.8.04.0000,3308902,0,Embargos de Declaração Cível / Indenização por...,Domingos Jorge Chalub Pereira,Manaus,Terceira Câmara Cível,17/06/2024,12/07/2024,EMBARGOS DE DECLARAÇÃO – AUSÊNCIA DE OMISSÃO –...
2,0746976-04.2021.8.04.0001,3307812,0,Apelação Cível / Revisão,Délcio Luís Santos,Manaus,Segunda Câmara Cível,24/06/2024,08/07/2024,APELAÇÃO CÍVEL. AÇÃO DE REVISÃO CONTRATUAL CUM...

## Download and parse separately

You can also download the raw HTML files and parse them in a separate step.

In [6]:
import tempfile, os

tmp = tempfile.mkdtemp()
pasta = tjam.cjsg_download('direito', paginas=1, diretorio=tmp)
print('Downloaded to:', pasta)
print('Files:', os.listdir(pasta))

Downloaded to: C:\Users\jtrec\AppData\Local\Temp\tmps2ze6xni\cjsg\20260409100832
Files: ['cjsg_00001.html']

In [7]:
df_parsed = tjam.cjsg_parse(pasta)
print(df_parsed.shape)
df_parsed.head(3)

Processando CJSG TJAM: 100%|██████████| 1/1 [00:00<00:00, 28.65it/s]

(10, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0708349-62.2020.8.04.0001,3363939,0,Apelação Cível / Indenização por Dano Material,Délcio Luís Santos,Manaus,Segunda Câmara Cível,25/11/2024,18/09/2025,APELAÇÕES CÍVEIS. DIREITO CIVIL. DIREITO CONSU...
1,0515824-48.2023.8.04.0001,3363938,0,Apelação Cível / Limitação de Juros,Domingos Jorge Chalub Pereira,Manaus,Terceira Câmara Cível,29/07/2025,29/07/2025,em>DIREITO DO CONSUMIDOR E PROCESSUAL CIVIL – ...
2,0006912-88.2024.8.04.0000,3363937,0,Agravo Interno Cível / Cartão de Crédito,Socorro Guedes Moura,Manaus,Segunda Câmara Cível,01/06/2004,16/07/2025,DIREITO DO CONSUMIDOR. AGRAVO INTERNO. CONTRAT...