# TJAP - Tribunal de Justica do Amapa

Scraper for the jurisprudence search of the Court of Justice of the State of Amapa (TJAP).
Uses the [Tucujuris](https://tucujuris.tjap.jus.br) platform with a JSON REST API.

| Feature | Available |
|---------|-----------|
| cjsg    | Yes       |
| cpopg   | No        |
| cposg   | No        |

In [1]:
import juscraper as jus

# Create the TJAP scraper
tjap = jus.scraper('tjap')

## Basic search

In [2]:
# Search for jurisprudence
dados_cjsg = tjap.cjsg('dano moral', paginas=range(1, 3))

print(dados_cjsg.shape)
dados_cjsg.head(3)

Baixando CJSG TJAP: 100%|██████████| 2/2 [00:21<00:00, 10.58s/it]

(40, 13)

,processo,numero_acordao,classe,relator,lotacao,comarca,votacao,data_julgamento,data_publicacao,ementa,id,identificador,data_registro
0,6056391-35.2025.8.03.0001,6618532,RECURSO INOMINADO CÍVEL,JOSE LUCIANO DE ASSIS,Turma Recursal,MACAPÁ,Unânime,2026-04-07,NaT,DIREITO DO CONSUMIDOR E BANCÁRIO. RECURSO INOM...,291328,6618532,2026-04-07
1,6066305-60.2024.8.03.0001,6614373,RECURSO INOMINADO CÍVEL,REGINALDO GOMES DE ANDRADE,Turma Recursal,MACAPÁ,Unânime,2026-04-06,NaT,DIREITO DO CONSUMIDOR E ADMINISTRATIVO. RECURS...,291322,6614373,2026-04-06
2,6080611-97.2025.8.03.0001,6614382,RECURSO INOMINADO CÍVEL,REGINALDO GOMES DE ANDRADE,Turma Recursal,MACAPÁ,Unânime,2026-04-06,NaT,DIREITO CIVIL E DO CONSUMIDOR. RECURSO INOMINA...,291327,6614382,2026-04-06

## Available columns

In [3]:
dados_cjsg.columns.tolist()

['processo',
 'numero_acordao',
 'classe',
 'relator',
 'lotacao',
 'comarca',
 'votacao',
 'data_julgamento',
 'data_publicacao',
 'ementa',
 'id',
 'identificador',
 'data_registro']

## Preview ementa

In [4]:
print(dados_cjsg['ementa'].iloc[0][:300])

DIREITO DO CONSUMIDOR E BANCÁRIO. RECURSO INOMINADO. CONTRATAÇÃO ILEGAL DE EMPRÉSTIMO. RESPONSABILIDADE OBJETIVA DE INSTITUIÇÃO FINANCEIRA. VÍCIO NA PRESTAÇÃO DO SERVIÇO. LEI ESTADUAL N&ordm; 2.840/2023 (AP). NULIDADE DO CONTRATO POR AUSÊNCIA DE ASSINATURA FÍSICA DE IDOSA. REPARAÇÃO DE DANOS MATERIA

## Using filters

The TJAP scraper supports several filters: orgao (court body), relator, classe, secretaria, origem, votacao, and more.

In [5]:
# Filter by orgao (Tribunal only)
dados_filtrados = tjap.cjsg(
    'dano moral',
    orgao='tj',
    paginas=1,
)

print(dados_filtrados.shape)
dados_filtrados.head(3)

Baixando CJSG TJAP: 100%|██████████| 1/1 [00:26<00:00, 26.34s/it]

(20, 13)

,processo,numero_acordao,classe,relator,lotacao,comarca,votacao,data_julgamento,data_publicacao,ementa,id,identificador,data_registro
0,6056391-35.2025.8.03.0001,6618532,RECURSO INOMINADO CÍVEL,JOSE LUCIANO DE ASSIS,Turma Recursal,MACAPÁ,Unânime,2026-04-07,NaT,DIREITO DO CONSUMIDOR E BANCÁRIO. RECURSO INOM...,291328,6618532,2026-04-07
1,6080611-97.2025.8.03.0001,6614382,RECURSO INOMINADO CÍVEL,REGINALDO GOMES DE ANDRADE,Turma Recursal,MACAPÁ,Unânime,2026-04-06,NaT,DIREITO CIVIL E DO CONSUMIDOR. RECURSO INOMINA...,291327,6614382,2026-04-06
2,6066305-60.2024.8.03.0001,6614373,RECURSO INOMINADO CÍVEL,REGINALDO GOMES DE ANDRADE,Turma Recursal,MACAPÁ,Unânime,2026-04-06,NaT,DIREITO DO CONSUMIDOR E ADMINISTRATIVO. RECURS...,291322,6614373,2026-04-06

## Download and parse separately

You can also download the raw JSON responses and parse them in a second step.

In [6]:
# Download raw JSON responses
brutos = tjap.cjsg_download('dano moral', paginas=1)

# Inspect the raw response structure
print(f"Number of pages downloaded: {len(brutos)}")
print(f"Status: {brutos[0]['status']}")
print(f"Results in first page: {len(brutos[0]['dados'])}")

Baixando CJSG TJAP: 100%|██████████| 1/1 [00:10<00:00, 10.44s/it]

Number of pages downloaded: 1
Status: OK
Results in first page: 20

In [7]:
# Parse raw responses into a DataFrame
df_parsed = tjap.cjsg_parse(brutos)

print(df_parsed.shape)
df_parsed.head(3)

(20, 13)

,processo,numero_acordao,classe,relator,lotacao,comarca,votacao,data_julgamento,data_publicacao,ementa,id,identificador,data_registro
0,6056391-35.2025.8.03.0001,6618532,RECURSO INOMINADO CÍVEL,JOSE LUCIANO DE ASSIS,Turma Recursal,MACAPÁ,Unânime,2026-04-07,NaT,DIREITO DO CONSUMIDOR E BANCÁRIO. RECURSO INOM...,291328,6618532,2026-04-07
1,6066305-60.2024.8.03.0001,6614373,RECURSO INOMINADO CÍVEL,REGINALDO GOMES DE ANDRADE,Turma Recursal,MACAPÁ,Unânime,2026-04-06,NaT,DIREITO DO CONSUMIDOR E ADMINISTRATIVO. RECURS...,291322,6614373,2026-04-06
2,6028640-73.2025.8.03.0001,6613886,RECURSO INOMINADO CÍVEL,REGINALDO GOMES DE ANDRADE,Turma Recursal,MACAPÁ,Unânime,2026-04-06,NaT,PROCESSUAL CIVIL. EMBARGOS DE DECLARAÇÃO. AUSÊ...,291307,6613886,2026-04-06