---
title: TJBA
---

# TJBA - Tribunal de Justica do Estado da Bahia

Scraper for the jurisprudence search of TJBA.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |
| cpopg   | No       |
| cposg   | No       |

## Basic search

In [1]:
import juscraper as jus

tjba = jus.scraper('tjba')

df = tjba.cjsg('dano moral', paginas=1)
print(df.shape)
df.head(3)

Baixando paginas TJBA: 100%|██████████| 1/1 [00:00<00:00,  1.15it/s]

(10, 11)

,processo,relator,orgao_julgador,classe,tipo_decisao,data_publicacao,ementa,hash,relator_id,orgao_julgador_id,classe_id
0,8000948-61.2020.8.05.0041,ALBERTO RAIMUNDO GOMES DOS SANTOS,TERCEIRA CAMARA CÍVEL,Apelação,ACORDAO,2025-12-30,PODER JUDICIÁRIO TRIBUNAL DE JUSTIÇA DO ESTAD...,99a2592c-871d-3616-94b9-06726f04a507,137,9,198
1,0008415-21.2025.8.05.0150,IVANA CARVALHO SILVA FERNANDES,TERCEIRA TURMA RECURSAL,Recurso Inominado,ACORDAO,2025-12-29,Tribunal de Justiça do Estado da Bahia PODER...,cc24fd37-c6f7-3287-aca3-583708bf3a10,76,4,460
2,0162755-79.2025.8.05.0001,IVANA CARVALHO SILVA FERNANDES,TERCEIRA TURMA RECURSAL,Recurso Inominado,ACORDAO,2025-12-29,Tribunal de Justiça do Estado da Bahia PODER...,f82db94e-1dd1-37fa-8a43-e4c662b5ad99,76,4,460

## Available columns

In [2]:
df.columns.tolist()

['processo',
 'relator',
 'orgao_julgador',
 'classe',
 'tipo_decisao',
 'data_publicacao',
 'ementa',
 'hash',
 'relator_id',
 'orgao_julgador_id',
 'classe_id']

## Preview ementa

In [3]:
print(df['ementa'].iloc[0][:300])

PODER JUDICIÁRIO TRIBUNAL  DE JUSTIÇA DO ESTADO DA BAHIA   Terceira Câmara Cível  Processo: APELAÇÃO CÍVEL n. 8000948-61.2020.8.05.0041 Órgão Julgador: Terceira Câmara Cível APELANTE: EVERISSIMO FRANCISCO DA GAMA Advogado(s): MICHELLE GODINHO DOS SANTOS, MICHEL GODINHO DOS SANTOS, CAROLINA RODRIGUES

## Using filters

TJBA supports filtering by publication date range.

In [4]:
df_filtrado = tjba.cjsg(
    'direito',
    data_publicacao_inicio='2024-01-01',
    data_publicacao_fim='2024-06-30',
    paginas=1,
)
print(df_filtrado.shape)
df_filtrado.head(3)

Baixando paginas TJBA: 100%|██████████| 1/1 [00:00<00:00,  5.64it/s]

(10, 11)

,processo,relator,orgao_julgador,classe,tipo_decisao,data_publicacao,ementa,hash,relator_id,orgao_julgador_id,classe_id
0,8003427-28.2021.8.05.0191,REGINA HELENA SANTOS E SILVA,TERCEIRA CAMARA CÍVEL,Apelação,ACORDAO,2024-06-30,PODER JUDICIÁRIO TRIBUNAL DE JUSTIÇA DO ESTAD...,2f3f5732-ff28-37ea-981c-c8dcae2ba224,196,9,198
1,0533133-36.2015.8.05.0001,LICIA PINTO FRAGOSO MODESTO,TERCEIRA CAMARA CÍVEL,Apelação,ACORDAO,2024-06-30,PODER JUDICIÁRIO TRIBUNAL DE JUSTIÇA DO ESTAD...,9ef8e2e2-7167-3094-9e19-47d76ee586dc,224,9,198
2,0033597-05.2024.8.05.0001,MARTHA CAVALCANTI SILVA DE OLIVEIRA,QUARTA TURMA RECURSAL,Recurso Inominado,ACORDAO,2024-06-30,Tribunal de Justiça do Estado da Bahia PODER J...,3bb05da8-93cb-3f1d-859b-fd9197db1e13,2,2,460

## Filtering by decision type

You can filter by instance (2nd degree, turmas recursais) and decision type (acordaos, monocratic decisions).

In [5]:
# Only acordaos from 2nd degree
df_acordaos = tjba.cjsg(
    'direito',
    segundo_grau=True,
    turmas_recursais=False,
    tipo_acordaos=True,
    tipo_decisoes_monocraticas=False,
    paginas=1,
)
print(df_acordaos.shape)
df_acordaos['tipo_decisao'].value_counts()

Baixando paginas TJBA: 100%|██████████| 1/1 [00:00<00:00,  4.20it/s]

(10, 11)

tipo_decisao
ACORDAO    10
Name: count, dtype: int64

## Download and parse separately

In [6]:
# Download raw results
brutos = tjba.cjsg_download('direito', paginas=1)

# Inspect raw response structure
print(type(brutos), len(brutos))
print(brutos[0]['data']['filter'].keys())

# Parse into DataFrame
df_parsed = tjba.cjsg_parse(brutos)
df_parsed.head(3)

Baixando paginas TJBA: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]

<class 'list'> 1
dict_keys(['decisoes', 'relatores', 'orgaos', 'classes', 'pageCount', 'itemCount'])

,processo,relator,orgao_julgador,classe,tipo_decisao,data_publicacao,ementa,hash,relator_id,orgao_julgador_id,classe_id
0,0088402-40.2003.8.05.0001,ALBERTO RAIMUNDO GOMES DOS SANTOS,TERCEIRA CAMARA CÍVEL,Apelação,ACORDAO,2025-12-30,PODER JUDICIÁRIO TRIBUNAL DE JUSTIÇA DO ESTAD...,2b58835f-7b6a-332c-b8cd-8aebe0658c8a,137,9,198
1,8000948-61.2020.8.05.0041,ALBERTO RAIMUNDO GOMES DOS SANTOS,TERCEIRA CAMARA CÍVEL,Apelação,ACORDAO,2025-12-30,PODER JUDICIÁRIO TRIBUNAL DE JUSTIÇA DO ESTAD...,99a2592c-871d-3616-94b9-06726f04a507,137,9,198
2,0094763-04.2025.8.05.0001,IVANA CARVALHO SILVA FERNANDES,TERCEIRA TURMA RECURSAL,Recurso Inominado,ACORDAO,2025-12-29,Tribunal de Justiça do Estado da Bahia PODER...,13c495ef-fd0c-39d6-b65f-0b38d08061e7,76,4,460