# TJGO — Court of Justice of Goiás

Scraper for the TJGO jurisprudence search hosted on Projudi
(`ConsultaJurisprudencia`). The page renders a Cloudflare Turnstile
widget but the backend does not validate the token, so the scraper
works with pure HTTP requests.

In [1]:
import juscraper as jus

tjgo = jus.scraper('tjgo')

## Basic search

Download two pages of results so we can verify pagination works.

In [2]:
df = tjgo.cjsg('dano moral', paginas=range(1, 3))
print(df.shape)
df.head(3)

(20, 7)

,processo,id_arquivo,serventia,relator,tipo_ato,data_publicacao,texto
0,5316968-04.2026.8.09.0100,517548028,Luziânia - Plantão da macrorregião 06,ILANNA ROSA DANTAS LENTS - (MAGISTRADO UPJ PRI...,Decisão,2026-04-12,ESTADO DE GOIÁS - PODER JUDICIÁRIOPlantão Regi...
1,5306107-32.2026.8.09.0011,517547816,"Aparecida de Goiânia - UPJ Varas Cíveis: 1ª, 2...",ALUIZIO MARTINS PEREIRA DE SOUZA,Decisão,2026-04-12,Estado de Goiás Poder Judiciário Comarca de Ap...
2,5317044-78.2026.8.09.0051,517547724,Goiânia - Plantão da Macrorregião 01,SIMONE MONTEIRO - (MAGISTRADO UPJ PRIMEIRO GRAU),Decisão,2026-04-12,PODER JUDICIÁRIO Plantão Judicial da Macrorreg...

## Available columns

In [3]:
df.columns.tolist()

['processo',
 'id_arquivo',
 'serventia',
 'relator',
 'tipo_ato',
 'data_publicacao',
 'texto']

## Text preview

In [4]:
print(df['texto'].iloc[0][:300])

ESTADO DE GOIÁS - PODER JUDICIÁRIOPlantão Regionalizado - Macrorregião 06Águas Lindas de Goiás, Alexânia, Cidade Ocidental, Cristalina, Luziânia, Novo Gama, Padre Bernardo, Santo Antônio do Descoberto e Valparaíso de GoiásDECISÃOAutos n.: 5316968-04.2026.8.09.0100Classe: PROCESSO CRIMINAL -> Procedi

## Filtering by instance and area

The search form exposes dropdowns that we can map directly:

* ``id_instancia``: ``0`` all / ``1`` 1st degree / ``2`` recursal / ``3`` tribunal
* ``id_area``: ``0`` all / ``1`` civil / ``2`` criminal

In [5]:
df_civel = tjgo.cjsg('dano moral', paginas=1, id_instancia=3, id_area=1)
df_civel[['processo', 'serventia', 'tipo_ato']].head()

,processo,serventia,tipo_ato
0,5316968-04.2026.8.09.0100,Luziânia - Plantão da macrorregião 06,Decisão
1,5306107-32.2026.8.09.0011,"Aparecida de Goiânia - UPJ Varas Cíveis: 1ª, 2...",Decisão
2,5317044-78.2026.8.09.0051,Goiânia - Plantão da Macrorregião 01,Decisão
3,5059938-45.2026.8.09.0051,Goiânia - 2ª UPJ Juizados Especiais Cíveis: 6º...,Sentença
4,6051993-24.2025.8.09.0051,Goiânia - 2ª UPJ Juizados Especiais Cíveis: 6º...,Sentença

## Download and parse separately

`cjsg_download` returns the raw HTML responses, which is useful when
you want to keep the original payloads.

In [6]:
raw = tjgo.cjsg_download('dano moral', paginas=1)
print(type(raw), len(raw), 'chars in page 1:', len(raw[0]))
df_raw = tjgo.cjsg_parse(raw)
df_raw.head(3)

<class 'list'> 1 chars in page 1: 177754

,processo,id_arquivo,serventia,relator,tipo_ato,data_publicacao,texto
0,5316968-04.2026.8.09.0100,517548028,Luziânia - Plantão da macrorregião 06,ILANNA ROSA DANTAS LENTS - (MAGISTRADO UPJ PRI...,Decisão,2026-04-12,ESTADO DE GOIÁS - PODER JUDICIÁRIOPlantão Regi...
1,5306107-32.2026.8.09.0011,517547816,"Aparecida de Goiânia - UPJ Varas Cíveis: 1ª, 2...",ALUIZIO MARTINS PEREIRA DE SOUZA,Decisão,2026-04-12,Estado de Goiás Poder Judiciário Comarca de Ap...
2,5317044-78.2026.8.09.0051,517547724,Goiânia - Plantão da Macrorregião 01,SIMONE MONTEIRO - (MAGISTRADO UPJ PRIMEIRO GRAU),Decisão,2026-04-12,PODER JUDICIÁRIO Plantão Judicial da Macrorreg...