# TJMS - Tribunal de Justica de Mato Grosso do Sul

Scraper for the jurisprudence search (CJSG) of the Tribunal de Justica de Mato Grosso do Sul.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |
| cpopg   | No       |
| cposg   | No       |

## Basic search

In [1]:
import juscraper as jus

tjms = jus.scraper('tjms')

In [2]:
df = tjms.cjsg('dano moral', paginas=range(1, 3))
print(df.shape)
df.head(3)

Baixando CJSG TJMS: 100%|██████████| 2/2 [00:01<00:00,  1.62s/it]
Processando CJSG TJMS: 100%|██████████| 2/2 [00:00<00:00,  6.27it/s]

(200, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0800633-13.2024.8.12.0006,1873656,0,Apelação Cível / Obrigação de Fazer / Não Fazer,Des. Marcelo Câmara Rasslan,Camapuã,1ª Câmara Cível,07/04/2026,09/04/2026,APELAÇÃO CÍVEL – AÇÃO DE OBRIGAÇÃO DE FAZER CU...
1,0816158-21.2022.8.12.0001,1873658,0,Embargos de Declaração Cível / Rescisão / Reso...,Juiz Fábio Possik Salamene,Campo Grande,3ª Câmara Cível,07/04/2026,09/04/2026,EMBARGOS DE DECLARAÇÃO EM APELAÇÃO CÍVEL – AÇÃ...
2,0800410-78.2025.8.12.0021,1873674,0,Embargos de Declaração Cível / Obrigação de Fa...,Juiz Fábio Possik Salamene,Três Lagoas,3ª Câmara Cível,07/04/2026,09/04/2026,EMBARGOS DE DECLARAÇÃO APELAÇÃO CÍVEL. INEXIS...

## Available columns

In [3]:
df.columns.tolist()

['processo',
 'cd_acordao',
 'cd_foro',
 'classe_assunto',
 'relatora',
 'comarca',
 'orgao_julgador',
 'data_julgamento',
 'data_publicacao',
 'ementa']

## Preview ementa

In [4]:
print(df['ementa'].iloc[0][:300])

APELAÇÃO CÍVEL – AÇÃO DE OBRIGAÇÃO DE FAZER CUMULADA COM INDENIZAÇÃO – ACORDO DE DISSOLUÇÃO DE UNIÃO ESTÁVEL – TRANSFERÊNCIA DE VEÍCULO – CLÁUSULA COM TERMO INICIAL, SEM TERMO FINAL – ATRASO NA FORMALIZAÇÃO – POSSE ANTECIPADA DO BEM – LUCROS CESSANTES E DANOS MORAIS – SENTENÇA CONFIRMADA – RECURSO C

## Using filters

You can filter by judgment date, publication date, decision type, and other fields.

In [5]:
df_filtered = tjms.cjsg(
    'direito',
    data_julgamento_inicio='01/01/2024',
    data_julgamento_fim='30/06/2024',
    paginas=1,
)
print(df_filtered.shape)
df_filtered.head(3)

Processando CJSG TJMS: 100%|██████████| 1/1 [00:00<00:00,  7.51it/s]

(100, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0801606-23.2019.8.12.0012,1692937,0,Embargos de Declaração Cível / Fornecimento de...,Juiz Vitor Luis de Oliveira Guibo,Ivinhema,2ª Câmara Cível,31/01/2024,13/03/2025,EMBARGOS DE DECLARAÇÃO – APELAÇÃO CÍVEL – AÇÃO...
1,1407238-41.2024.8.12.0000,1580279,0,Agravo de Instrumento / Efeito Suspensivo / Im...,Des. Marcelo Câmara Rasslan,Camapuã,1ª Câmara Cível,18/06/2024,04/07/2024,AGRAVO DE INSTRUMENTO – CUMPRIMENTO DE SENTENÇ...
2,0047680-51.2012.8.12.0001,1578759,0,Embargos de Declaração Cível / Prestação de Se...,Des. Odemilson Roberto Castro Fassa,Campo Grande,3ª Câmara Cível,28/06/2024,02/07/2024,E M E N T A - EMBARGOS de DECLARAÇÃO DE USINA ...

## Download and parse separately

You can also download the raw HTML files and parse them in a separate step.

In [6]:
import tempfile, os

tmp = tempfile.mkdtemp()
pasta = tjms.cjsg_download('direito', paginas=1, diretorio=tmp)
print('Downloaded to:', pasta)
print('Files:', os.listdir(pasta))

Downloaded to: C:\Users\jtrec\AppData\Local\Temp\tmpzp9zc7ph\cjsg\20260409100838
Files: ['cjsg_00001.html']

In [7]:
df_parsed = tjms.cjsg_parse(pasta)
print(df_parsed.shape)
df_parsed.head(3)

Processando CJSG TJMS: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]

(100, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0802534-30.2022.8.12.0024,1873642,0,Agravo Interno Cível / Pagamento,Vice-Presidente,Aparecida do Taboado,Vice-Presidência,08/04/2026,09/04/2026,em>DIREITO ADMINISTRATIVO E PROCESSUAL CIVIL. ...
1,1414822-28.2025.8.12.0000,1873646,0,Agravo de Instrumento / Nulidade - Ausência de...,Des. Marcelo Câmara Rasslan,Ponta Porã,1ª Câmara Cível,07/04/2026,09/04/2026,AGRAVO DE INSTRUMENTO - AÇÃO CIVIL PÚBLICA POR...
2,0803111-31.2024.8.12.0026,1873649,0,Apelação Criminal / Tráfico de Drogas e Condut...,Des. José Ale Ahmad Netto,Bataguassu,2ª Câmara Criminal,07/04/2026,09/04/2026,em>DIREITO PENAL E PROCESSUAL PENAL. APELAÇÃO ...