# TJMT - Tribunal de Justica do Estado de Mato Grosso

Scraper for the jurisprudence search of TJMT.

| Feature | Status |
|---------|--------|
| cjsg (Acordao) | Supported |
| cjsg (Decisao Monocratica) | Supported |
| cpopg | Not implemented |
| cposg | Not implemented |

## Basic search

In [1]:
import juscraper as jus

tjmt = jus.scraper('tjmt')

dados_cjsg = tjmt.cjsg('dano moral', paginas=1)
print(dados_cjsg.shape)
dados_cjsg.head(3)

Baixando páginas TJMT: 100%|██████████| 1/1 [00:01<00:00,  1.34s/it]

(10, 18)

,id,tipo,ementa,observacao,numero_unico,classe,assunto,tipo_acao,tipo_processo,relator,redator_designado,orgao_julgador,sigla_classe_feito,data_julgamento,data_publicacao,instancia,origem,julgamento
0,358068885,Acordao,EMENTA: DIREITO PROCESSUAL CIVIL E DIREITO DO ...,"(N.U 1045934-10.2025.8.11.0000, CÂMARAS ISOLAD...",1045934-10.2025.8.11.0000,EMBARGOS DE DECLARAÇÃO CÍVEL,Substituição do Produto,DIREITO DO CONSUMIDOR (1156) \ Responsabilidad...,Cível,RUBENS DE OLIVEIRA SANTOS FILHO,None,Quarta Câmara de Direito Privado,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PRIVADO,2026-04-01,2026-04-01,Segunda,PJe,NÃO INFORMADO
1,358103897,Acordao,EMENTA DIREITO PROCESSUAL CIVIL. AGRAVO DE INS...,"(N.U 1007056-79.2026.8.11.0000, CÂMARAS ISOLAD...",1007056-79.2026.8.11.0000,AGRAVO DE INSTRUMENTO,Obrigação de Fazer / Não Fazer,DIREITO PROCESSUAL CIVIL E DO TRABALHO (8826) ...,Cível,SERLY MARCONDES ALVES,None,Quarta Câmara de Direito Privado,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PRIVADO,2026-04-01,2026-04-01,Segunda,PJe,NÃO INFORMADO
2,358020366,Acordao,DIREITO PROCESSUAL CIVIL. EMBARGOS DE DECLARAÇ...,"(N.U 0002028-90.2017.8.11.0024, CÂMARAS ISOLAD...",0002028-90.2017.8.11.0024,EMBARGOS DE DECLARAÇÃO CÍVEL,Prestação de Serviços,DIREITO CIVIL (899) \ Obrigações (7681) \ Espé...,Cível,ANGLIZEY SOLIVAN DE OLIVEIRA,None,Quarta Câmara de Direito Privado,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PRIVADO,2026-04-01,2026-04-01,Segunda,PJe,NÃO INFORMADO

## Available columns

In [2]:
dados_cjsg.columns.tolist()

['id',
 'tipo',
 'ementa',
 'observacao',
 'numero_unico',
 'classe',
 'assunto',
 'tipo_acao',
 'tipo_processo',
 'relator',
 'redator_designado',
 'orgao_julgador',
 'sigla_classe_feito',
 'data_julgamento',
 'data_publicacao',
 'instancia',
 'origem',
 'julgamento']

## Preview ementa

In [3]:
print(dados_cjsg['ementa'].iloc[0][:300])

EMENTA: DIREITO PROCESSUAL CIVIL E DIREITO DO CONSUMIDOR. EMBARGOS DE DECLARAÇÃO. AGRAVO DE INSTRUMENTO. JULGAMENTO ANTECIPADO PARCIAL DO MÉRITO. ALEGAÇÃO DE ERRO DE FATO, CONTRADIÇÃO E OMISSÃO. INEXISTÊNCIA DE VÍCIOS. ARGUMENTAÇÃO SUBSIDIÁRIA NÃO CONFIGURA RECONHECIMENTO DO PEDIDO. EMBARGOS REJEITA

## Using filters

You can filter by date range, judge (relator), court chamber (orgao_julgador), and case type (tipo_processo).

In [4]:
dados_filtrados = tjmt.cjsg(
    'direito',
    paginas=1,
    data_julgamento_inicio='2025-01-01',
    data_julgamento_fim='2025-06-30',
    tipo_processo='Criminal',
)
print(dados_filtrados.shape)
dados_filtrados.head(3)

Baixando páginas TJMT: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s]

(10, 18)

,id,tipo,ementa,observacao,numero_unico,classe,assunto,tipo_acao,tipo_processo,relator,redator_designado,orgao_julgador,sigla_classe_feito,data_julgamento,data_publicacao,instancia,origem,julgamento
0,357998889,Acordao,PRIMEIRA CÂMARA CRIMINALAPELAÇÃO CRIMINAL (417...,"(N.U 1001710-20.2021.8.11.0002, CÂMARAS ISOLAD...",1001710-20.2021.8.11.0002,APELAÇÃO CRIMINAL,Homicídio Qualificado,DIREITO PENAL (287) \ Crimes contra a vida (33...,Criminal,ORLANDO DE ALMEIDA PERRI,None,Primeira Câmara Criminal,CÂMARAS ISOLADAS CRIMINAIS,2026-04-01,2026-04-01,Segunda,PJe,NÃO INFORMADO
1,358024367,Acordao,Ementa: Direito penal e processual penal. Agra...,"(N.U 1043828-75.2025.8.11.0000, CÂMARAS ISOLAD...",1043828-75.2025.8.11.0000,AGRAVO DE EXECUÇÃO PENAL,Pena Privativa de Liberdade,DIREITO PROCESSUAL PENAL (1209) \ Execução Pen...,Criminal,MARCOS MACHADO,None,Primeira Câmara Criminal,CÂMARAS ISOLADAS CRIMINAIS,2026-04-01,2026-04-01,Segunda,PJe,NÃO INFORMADO
2,358024398,Acordao,Ementa: Direito penal e processual penal. Apel...,"(N.U 0000017-28.2019.8.11.0086, CÂMARAS ISOLAD...",0000017-28.2019.8.11.0086,APELAÇÃO CRIMINAL,Homicídio Qualificado,DIREITO PENAL (287) \ Crimes contra a vida (33...,Criminal,MARCOS MACHADO,None,Primeira Câmara Criminal,CÂMARAS ISOLADAS CRIMINAIS,2026-04-01,2026-04-01,Segunda,PJe,NÃO INFORMADO

## Querying different types

Besides `Acordao` (default), you can also query `DecisaoMonocratica`.

In [5]:
dados_decisao = tjmt.cjsg('direito', paginas=1, tipo_consulta='DecisaoMonocratica')
print(dados_decisao.shape)
dados_decisao.head(3)

Baixando páginas TJMT: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s]

(10, 18)

,id,tipo,ementa,observacao,numero_unico,classe,assunto,tipo_acao,tipo_processo,relator,redator_designado,orgao_julgador,sigla_classe_feito,data_julgamento,data_publicacao,instancia,origem,julgamento
0,358297875,DecisaoMonocratica,ESTADO DE MATO GROSSOPODER JUDICIÁRIOTRIBUNAL ...,"(N.U 1014565-61.2026.8.11.0000, CÂMARAS ISOLAD...",1014565-61.2026.8.11.0000,AGRAVO DE INSTRUMENTO,Análise de Crédito,DIREITO DO CONSUMIDOR (1156) \ Responsabilidad...,Cível,WALTER PEREIRA DE SOUZA,None,Secretaria de Plantão das Turmas Recursais,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PÚBLICO,2026-04-03,NaT,Segunda,PJe,NÃO INFORMADO
1,358298358,DecisaoMonocratica,ESTADO DE MATO GROSSOPODER JUDICIÁRIOTRIBUNAL ...,"(N.U 1014565-61.2026.8.11.0000, CÂMARAS ISOLAD...",1014565-61.2026.8.11.0000,AGRAVO DE INSTRUMENTO,Análise de Crédito,DIREITO DO CONSUMIDOR (1156) \ Responsabilidad...,Cível,WALTER PEREIRA DE SOUZA,None,Secretaria de Plantão das Turmas Recursais,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PÚBLICO,2026-04-03,NaT,Segunda,PJe,NÃO INFORMADO
2,357978363,DecisaoMonocratica,ESTADO DE MATO GROSSOPODER JUDICIÁRIOTRIBUNAL ...,"(N.U 1038264-89.2025.8.11.0041, CÂMARAS ISOLAD...",1038264-89.2025.8.11.0041,APELAÇÃO CÍVEL,Empréstimo consignado,DIREITO DO CONSUMIDOR (1156) \ Contratos de Co...,Cível,HELIO NISHIYAMA,None,Segunda Câmara de Direito Privado,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PRIVADO,2026-04-02,2026-04-02,Segunda,PJe,NÃO INFORMADO

## Download and parse separately

You can also download the raw data first and parse it later.

In [6]:
brutos = tjmt.cjsg_download('direito', paginas=1)
print(f"Pages downloaded: {len(brutos)}")
print(f"Keys in response: {list(brutos[0].keys())}")

dados = tjmt.cjsg_parse(brutos)
import pandas as pd
df = pd.DataFrame(dados)
print(f"\nParsed shape: {df.shape}")
df.head(3)

Baixando páginas TJMT: 100%|██████████| 1/1 [00:00<00:00,  1.26it/s]

Pages downloaded: 1
Keys in response: ['AcordaoCollection', 'DecisaoMonocraticaCollection', 'ResumoProcessoCollection', 'RecursalEletronicoCollection', 'ThesaurusTermosCollection', 'CountAcordaoDocumento', 'CountDecisaoMonocratica', 'CountResumoProcesso', 'CountRecursalEletronico', 'CountTotal', 'FacetRedatorDesignado', 'FacetCamara', 'FacetTipoProcesso', 'FacetRelator', 'FacetAssunto', 'FacetJulgamento']

Parsed shape: (10, 18)

,id,tipo,ementa,observacao,numero_unico,classe,assunto,tipo_acao,tipo_processo,relator,redator_designado,orgao_julgador,sigla_classe_feito,data_julgamento,data_publicacao,instancia,origem,julgamento
0,358287882,Acordao,EMENTA DIREITO CIVIL E PROCESSUAL CIVIL. EMBAR...,"(N.U 1042706-27.2025.8.11.0000, CÂMARAS ISOLAD...",1042706-27.2025.8.11.0000,EMBARGOS DE DECLARAÇÃO CÍVEL,Inventário e Partilha,DIREITO CIVIL (899) \ Sucessões (7673) \ Inven...,Cível,SERLY MARCONDES ALVES,None,Quarta Câmara de Direito Privado,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PRIVADO,2026-04-01T00:00:00,2026-04-02T00:00:00,Segunda,PJe,NÃO INFORMADO
1,358074862,Acordao,TERCEIRA CÂMARA DE DIREITO PRIVADOAPELAÇÃO CÍV...,"(N.U 1017072-57.2020.8.11.0015, CÂMARAS ISOLAD...",1017072-57.2020.8.11.0015,APELAÇÃO CÍVEL,Esbulho / Turbação / Ameaça,DIREITO CIVIL (899) \ Coisas (10432) \ Posse (...,Cível,ANTONIA SIQUEIRA GONCALVES,None,Terceira Câmara de Direito Privado,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PRIVADO,2026-04-01T00:00:00,2026-04-01T00:00:00,Segunda,PJe,NÃO INFORMADO
2,358289370,Acordao,EMENTA DIREITO PROCESSUAL CIVIL. AGRAVO DE INS...,"(N.U 1004943-55.2026.8.11.0000, CÂMARAS ISOLAD...",1004943-55.2026.8.11.0000,AGRAVO DE INSTRUMENTO,Compra e Venda,DIREITO CIVIL (899) \ Obrigações (7681) \ Espé...,Cível,SERLY MARCONDES ALVES,None,Quarta Câmara de Direito Privado,CÂMARAS ISOLADAS CÍVEIS DE DIREITO PRIVADO,2026-04-01T00:00:00,2026-04-02T00:00:00,Segunda,PJe,NÃO INFORMADO