# TJPA - Tribunal de Justica do Estado do Para

Scraper for the jurisprudence search of the Court of Justice of the State of Para (TJPA).

| Feature | Available |
|---------|-----------|
| cjsg    | Yes       |
| cpopg   | No        |
| cposg   | No        |

## Basic search

In [1]:
import juscraper as jus

# Create the TJPA scraper
tjpa = jus.scraper('tjpa')

In [8]:
# Search for jurisprudence
dados_cjsg = tjpa.cjsg('dano moral', paginas=range(1,3))

print(dados_cjsg.shape)
dados_cjsg.head(3)

Baixando páginas TJPA: 100%|██████████| 2/2 [00:06<00:00,  3.15s/it]

(50, 21)

,processo,tipo,classe,assunto,relator,orgao_julgador_colegiado,data_julgamento,data_publicacao,ementa,id,...,origem,id_classe,id_assunto,orgao_julgador,competencia,data_documento,sentido_decisao,especie,sistema_origem,hash_storage
0,0008207-65.2016.8.14.0000,Decisão Monocrática,Agravo de Instrumento,Dissolução,MARIA FILOMENA DE ALMEIDA BUARQUE,1ª Turma de Direito Privado,NaT,NaT,,20170107834038,...,Tribunal de Justiça do Estado do Pará,202,7664,MARIA FILOMENA DE ALMEIDA BUARQUE,1ª Turma de Direito Privado,2017-03-27,None,JUDICIAL,Libra,None
1,0000107-79.2001.8.14.0035,Decisão Monocrática,Apelação Cível,Admissão / Permanência / Despedida,CONSTANTINO AUGUSTO GUERREIRO,2ª Turma de Direito Público,NaT,NaT,,20170122307408,...,Tribunal de Justiça do Estado do Pará,198,10411,CONSTANTINO AUGUSTO GUERREIRO,2ª Turma de Direito Público,2017-03-28,None,JUDICIAL,Libra,None
2,0038403-26.2002.8.14.0301,Decisão Monocrática,Apelação Cível,Cédula de Crédito Rural,RICARDO FERREIRA NUNES,4ª Camara Civel Isolada,NaT,NaT,,20170121753150,...,Tribunal de Justiça do Estado do Pará,198,4964,RICARDO FERREIRA NUNES,4ª Camara Civel Isolada,2017-03-28,None,JUDICIAL,Libra,None

## Available columns

In [3]:
dados_cjsg.columns.tolist()

['processo',
 'tipo',
 'classe',
 'assunto',
 'relator',
 'orgao_julgador_colegiado',
 'data_julgamento',
 'data_publicacao',
 'ementa',
 'id',
 'area',
 'origem',
 'id_classe',
 'id_assunto',
 'orgao_julgador',
 'competencia',
 'data_documento',
 'sentido_decisao',
 'especie',
 'sistema_origem',
 'hash_storage']

## Preview ementa

In [4]:
print(dados_cjsg['ementa'].iloc[0][:300])

## Using filters

The TJPA scraper supports several filters: date ranges, relator, collegiate judging body, class, and subject.

In [5]:
# Filter by judgment date range
dados_filtrados = tjpa.cjsg(
    'dano moral',
    data_julgamento_inicio='2024-01-01',
    data_julgamento_fim='2024-06-30',
    paginas=1,
)

print(dados_filtrados.shape)
dados_filtrados.head(3)

Baixando páginas TJPA: 100%|██████████| 1/1 [00:01<00:00,  1.78s/it]

(25, 21)

,processo,tipo,classe,assunto,relator,orgao_julgador_colegiado,data_julgamento,data_publicacao,ementa,id,...,origem,id_classe,id_assunto,orgao_julgador,competencia,data_documento,sentido_decisao,especie,sistema_origem,hash_storage
0,0801607-14.2024.8.14.0000,Acórdão,PETIÇÃO CÍVEL,Depósito,LUANA DE NAZARETH AMARAL HENRIQUES SANTALICES,Tribunal Pleno,2024-06-26,NaT,DÚVIDA NÃO MANIFESTADA NA FORMA DE CONFLITO DE...,20528771,...,Tribunal de Justiça do Estado do Pará,241,9589,Desembargadora LUANA DE NAZARETH AMARAL HENRIQ...,Tribunal Pleno de Direito Privado,2024-07-04,None,JUDICIAL,Processo Judicial Eletrônico - 2º Grau,cb07a46f94ed5a4b2c76adc5bac66d047415fc1e
1,0817223-63.2023.8.14.0000,Acórdão,INCIDENTE DE ASSUNÇÃO DE COMPETÊNCIA,Imunidade de Jurisdição,RICARDO FERREIRA NUNES,Tribunal Pleno,2024-06-26,NaT,INCIDENTE DE ASSUNÇÃO DE COMPETÊNCIA. JULGAMEN...,20373570,...,Tribunal de Justiça do Estado do Pará,12087,8838,Desembargador RICARDO FERREIRA NUNES,Tribunal Pleno de Direito Privado,2024-06-27,None,JUDICIAL,Processo Judicial Eletrônico - 2º Grau,009d1757cd383574c2192005459bc25f7082a868
2,0002595-65.2015.8.14.0006,Acórdão,APELAÇÃO CÍVEL,Locação de Móvel,AMILCAR ROBERTO BEZERRA GUIMARAES,2ª Turma de Direito Privado,2024-06-25,NaT,APELAÇÃO CÍVEL Nº 0002595-65.2015.8.14.0006 CO...,20699243,...,Tribunal de Justiça do Estado do Pará,198,9609,Desembargador AMILCAR ROBERTO BEZERRA GUIMARÃES,Turma de Direito Privado,2024-07-13,None,JUDICIAL,Processo Judicial Eletrônico - 2º Grau,0c3a35c97ade73440f4e2880ff78f77946187eaf

## Download and parse separately

You can also download the raw responses and parse them in a second step.

In [6]:
# Download raw JSON responses
brutos = tjpa.cjsg_download('dano moral', paginas=1)

# Inspect the raw response structure
print(f"Number of pages downloaded: {len(brutos)}")
print(f"Total results: {brutos[0]['data']['totalElements']}")
print(f"Results in first page: {len(brutos[0]['data']['content'])}")

Baixando páginas TJPA: 100%|██████████| 1/1 [00:03<00:00,  3.24s/it]

Number of pages downloaded: 1
Total results: 10000
Results in first page: 25

In [7]:
# Parse raw responses into a DataFrame
df_parsed = tjpa.cjsg_parse(brutos)

print(df_parsed.shape)
df_parsed.head(3)

(25, 21)

,processo,tipo,classe,assunto,relator,orgao_julgador_colegiado,data_julgamento,data_publicacao,ementa,id,...,origem,id_classe,id_assunto,orgao_julgador,competencia,data_documento,sentido_decisao,especie,sistema_origem,hash_storage
0,0008207-65.2016.8.14.0000,Decisão Monocrática,Agravo de Instrumento,Dissolução,MARIA FILOMENA DE ALMEIDA BUARQUE,1ª Turma de Direito Privado,NaT,NaT,,20170107834038,...,Tribunal de Justiça do Estado do Pará,202,7664,MARIA FILOMENA DE ALMEIDA BUARQUE,1ª Turma de Direito Privado,2017-03-27,None,JUDICIAL,Libra,None
1,0000107-79.2001.8.14.0035,Decisão Monocrática,Apelação Cível,Admissão / Permanência / Despedida,CONSTANTINO AUGUSTO GUERREIRO,2ª Turma de Direito Público,NaT,NaT,,20170122307408,...,Tribunal de Justiça do Estado do Pará,198,10411,CONSTANTINO AUGUSTO GUERREIRO,2ª Turma de Direito Público,2017-03-28,None,JUDICIAL,Libra,None
2,0038403-26.2002.8.14.0301,Decisão Monocrática,Apelação Cível,Cédula de Crédito Rural,RICARDO FERREIRA NUNES,4ª Camara Civel Isolada,NaT,NaT,,20170121753150,...,Tribunal de Justiça do Estado do Pará,198,4964,RICARDO FERREIRA NUNES,4ª Camara Civel Isolada,2017-03-28,None,JUDICIAL,Libra,None