# TJPB - Tribunal de Justica da Paraiba

Jurisprudence scraper for TJPB, using the PJe/TJRN JSON API.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |

In [6]:
import juscraper as jus

tjpb = jus.scraper('tjpb')

## Basic search

In [7]:
df = tjpb.cjsg('dano moral', paginas=1)

print(df.shape)
df.head(3)

Baixando CJSG TJPB: 100%|██████████| 1/1 [00:01<00:00,  1.55s/it]

(10, 3)

,processo,ementa,data_julgamento
0,0802057-88.2013.8.15.0751,Processo nº: 0802057-88.2013.8.15.0751 Class...,2017-07-07
1,0801625-33.2012.8.15.2003,RECURSO INOMINADO. Dano moral. Inscrição devid...,2017-03-30
2,0817132-35.2015.8.15.2001,RECURSO INOMINADO – AÇÃO DE INDENIZAÇÃO POR DA...,2017-01-11

## Available columns

In [8]:
brutos = tjpb.cjsg_download('dano moral', paginas=1)
df_parsed = tjpb.cjsg_parse(brutos)

print(df_parsed.shape)
df_parsed.head(3)

Baixando CJSG TJPB: 100%|██████████| 1/1 [00:01<00:00,  1.17s/it]

(10, 3)

,processo,ementa,data_julgamento
0,0802057-88.2013.8.15.0751,Processo nº: 0802057-88.2013.8.15.0751 Class...,2017-07-07
1,0801625-33.2012.8.15.2003,RECURSO INOMINADO. Dano moral. Inscrição devid...,2017-03-30
2,0817132-35.2015.8.15.2001,RECURSO INOMINADO – AÇÃO DE INDENIZAÇÃO POR DA...,2017-01-11

## Preview ementa

In [9]:
print(df['ementa'].iloc[0][:300])

  Processo nº: 0802057-88.2013.8.15.0751 Classe: RECURSO INOMINADO (460) Assuntos: [Indenização por Dano Moral, Indenização por Dano Moral] RECORRENTE: TNL PCS S/A RECORRIDO: CLAUDIA DE FATIMA DA SILVA

## Using filters

Available filters: `nr_processo`, `id_classe_judicial`, `id_orgao_julgador`, `id_relator`, `id_origem`, `decisoes`.

In [12]:
df_filtered = tjpb.cjsg(
    'direito',
    data_inicio='01/01/2024',
    data_fim='30/06/2024',
    paginas=range(1,3),
)

print(df_filtered.shape)
df_filtered.head(3)

Baixando CJSG TJPB: 100%|██████████| 2/2 [00:02<00:00,  1.18s/it]

(20, 3)

,processo,ementa,data_julgamento
0,0844756-88.2017.8.15.2001,Poder Judiciário Tribunal de Justiça da Paraíb...,2024-06-20
1,0800097-69.2021.8.15.0411,PODER JUDICIÁRIO TRIBUNAL DE JUSTIÇA DO ESTADO...,2024-05-29
2,0800310-59.2023.8.15.7701,Poder Judiciário Tribunal de Justiça da Paraíb...,2024-04-23