# TJPI - Tribunal de Justica do Piaui

Jurisprudence scraper for TJPI, via HTML parsing from the JusPI platform.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |

In [6]:
import juscraper as jus

tjpi = jus.scraper('tjpi')

## Basic search

In [7]:
df = tjpi.cjsg('dano moral', paginas=range(1, 3))

print(df.shape)
df.head(3)

Baixando CJSG TJPI: 100%|██████████| 2/2 [00:04<00:00,  2.39s/it]

(50, 8)

,processo,tipo,classe,assunto,data_publicacao,ementa,resumo,inteiro_teor
0,0800002-98.2022.8.18.0062,Decisão Terminativa de 2º Grau,APELAÇÃO CÍVEL,"Repetição de indébito, Direito de Imagem, Dire...",2025-09-02,AÇÃO DE INDENIZAÇÃO PORDANOSMORAISC/C REPETIÇÃ...,AÇÃO DE INDENIZAÇÃO POR,poder judiciário tribunal de justiça do estado...
1,0800942-44.2024.8.18.0078,Decisão Terminativa de 2º Grau,APELAÇÃO CÍVEL,Inclusão Indevida em Cadastro de Inadimplentes...,2025-09-02,poder judiciário tribunal de justiça do estado...,poder judiciário tribunal de justiça do estado...,poder judiciário tribunal de justiça do estado...
2,0011481-65.2013.8.18.0021,Decisão Terminativa de 2º Grau,RECURSO INOMINADO CÍVEL,Direito de Imagem,2025-09-02,AGRAVO DE INSTRUMENTO. CUMPRIMENTO SENTENÇA. A...,poder judiciário tribunal de justiça do estado...,poder judiciário tribunal de justiça do estado...

## Available columns

In [8]:
brutos = tjpi.cjsg_download('dano moral', paginas=1)
df_parsed = tjpi.cjsg_parse(brutos)

print(df_parsed.shape)
df_parsed.head(3)

Baixando CJSG TJPI: 100%|██████████| 1/1 [00:02<00:00,  2.29s/it]

(25, 8)

,processo,tipo,classe,assunto,data_publicacao,ementa,resumo,inteiro_teor
0,0800002-98.2022.8.18.0062,Decisão Terminativa de 2º Grau,APELAÇÃO CÍVEL,"Repetição de indébito, Direito de Imagem, Dire...",2025-09-02,AÇÃO DE INDENIZAÇÃO PORDANOSMORAISC/C REPETIÇÃ...,AÇÃO DE INDENIZAÇÃO POR,poder judiciário tribunal de justiça do estado...
1,0800942-44.2024.8.18.0078,Decisão Terminativa de 2º Grau,APELAÇÃO CÍVEL,Inclusão Indevida em Cadastro de Inadimplentes...,2025-09-02,poder judiciário tribunal de justiça do estado...,poder judiciário tribunal de justiça do estado...,poder judiciário tribunal de justiça do estado...
2,0011481-65.2013.8.18.0021,Decisão Terminativa de 2º Grau,RECURSO INOMINADO CÍVEL,Direito de Imagem,2025-09-02,AGRAVO DE INSTRUMENTO. CUMPRIMENTO SENTENÇA. A...,poder judiciário tribunal de justiça do estado...,poder judiciário tribunal de justiça do estado...

## Preview ementa

In [9]:
print(df['ementa'].iloc[0][:300])

AÇÃO DE INDENIZAÇÃO PORDANOSMORAISC/C REPETIÇÃO DE INDÉBITO. JUNTADA DE CONTRATO. NÃO COMPROVAÇÃO DE TRANSFERÊNCIA. APLICAÇÃO DA SÚMULA Nº 18 DO TJ/PI.DANOMORALCONFIGURADO. DEVOLUÇÃO DE VALORES. MÁ-FÉ CONFIGURADA.DANOMORALDEVIDO. RECURSO CONHECIDO E IMPROVIDO.   Vistos etc. Cuida-se de APELAÇÃO CÍVE

## Using filters

Available filters: `tipo` (acordao, decisao_terminativa, sumula), `relator`, `classe`, `orgao`.

In [10]:
df_filtered = tjpi.cjsg('direito', tipo='acordao', paginas=1)

print(df_filtered.shape)
df_filtered.head(3)

Baixando CJSG TJPI: 100%|██████████| 1/1 [00:01<00:00,  1.90s/it]

(0, 0)

Empty DataFrame
Columns: []
Index: []