# TJRJ — Court of Justice of Rio de Janeiro

Scraper for the TJRJ jurisprudence search (`ConsultarJurisprudencia.aspx`).
The site displays a reCAPTCHA widget but the backend does not validate it,
so the scraper works with pure HTTP requests.

In [1]:
import juscraper as jus

tjrj = jus.scraper('tjrj')

## Basic search

Download two pages of results so we can verify pagination works.

In [2]:
df = tjrj.cjsg('dano moral', ano_inicio=2024, ano_fim=2024, paginas=range(1, 3))
print(df.shape)
df.head(3)

(20, 10)

,cod_documento,processo,numero_antigo,classe,tipo_documento,orgao_julgador,relator,data_julgamento,data_publicacao,ementa
0,5424661,0102877-76.2024.8.19.0000,2024002151230,AGRAVO DE INSTRUMENTO,Decisão monocrática,PRIMEIRA CAMARA DE DIREITO PRIVADO (ANTIGA 8ª ...,Des(a). AUGUSTO ALVES MOREIRA JUNIOR,2024-12-21,None,AGRAVO DE INSTRUMENTO. DECISÃO PROFERIDA SOB A...
1,5424485,0015762-90.2020.8.19.0021,2024001136411,APELAÇÃO,Decisão monocrática,TERCEIRA CAMARA DE DIREITO PRIVADO (ANTIGA 18ª...,Des(a). LUIZ FERNANDO DE ANDRADE PINTO,2024-12-21,None,APELAÇÃO CÍVEL. CONSUMIDOR. CONSUMO DE ENERGIA...
2,5424488,0823838-32.2022.8.19.0205,2024001135342,APELAÇÃO,Decisão monocrática,TERCEIRA CAMARA DE DIREITO PRIVADO (ANTIGA 18ª...,Des(a). LUIZ FERNANDO DE ANDRADE PINTO,2024-12-28,None,APELAÇÃO CÍVEL. RELAÇÃO DE CONSUMO. TRANSAÇÕE...

## Available columns

In [3]:
df.columns.tolist()

['cod_documento',
 'processo',
 'numero_antigo',
 'classe',
 'tipo_documento',
 'orgao_julgador',
 'relator',
 'data_julgamento',
 'data_publicacao',
 'ementa']

## Ementa preview

In [4]:
print(df['ementa'].iloc[0][:300])

AGRAVO DE INSTRUMENTO. DECISÃO PROFERIDA SOB A ÉGIDE DO NOVO CÓDIGO DE PROCESSO CIVIL QUE NÃO SE ENQUADRA NAS HIPÓTESES PREVISTAS NO ARTIGO 1.015. ROL TAXATIVO. A SISTEMÁTICA PROCESSUAL ATUAL RESTRINGIU A INTERPOSIÇÃO DE AGRAVO DE INSTRUMENTO PARA AS HIPÓTESES DO ARTIGO 1.015 DO DIPLOMA PROCESSUAL E

## Download and parse separately

`cjsg_download` returns the raw JSON payloads from the server — useful when
you want to keep the original data.

In [5]:
raw = tjrj.cjsg_download('dano moral', ano_inicio=2024, ano_fim=2024, paginas=1)
print(type(raw), len(raw))
print('Total de documentos na base:', raw[0]['TotalDocs'])
df_raw = tjrj.cjsg_parse(raw)
df_raw.head(3)

<class 'list'> 1
Total de documentos na base: 78523

,cod_documento,processo,numero_antigo,classe,tipo_documento,orgao_julgador,relator,data_julgamento,data_publicacao,ementa
0,5424661,0102877-76.2024.8.19.0000,2024002151230,AGRAVO DE INSTRUMENTO,Decisão monocrática,PRIMEIRA CAMARA DE DIREITO PRIVADO (ANTIGA 8ª ...,Des(a). AUGUSTO ALVES MOREIRA JUNIOR,2024-12-21,None,AGRAVO DE INSTRUMENTO. DECISÃO PROFERIDA SOB A...
1,5424485,0015762-90.2020.8.19.0021,2024001136411,APELAÇÃO,Decisão monocrática,TERCEIRA CAMARA DE DIREITO PRIVADO (ANTIGA 18ª...,Des(a). LUIZ FERNANDO DE ANDRADE PINTO,2024-12-21,None,APELAÇÃO CÍVEL. CONSUMIDOR. CONSUMO DE ENERGIA...
2,5424488,0823838-32.2022.8.19.0205,2024001135342,APELAÇÃO,Decisão monocrática,TERCEIRA CAMARA DE DIREITO PRIVADO (ANTIGA 18ª...,Des(a). LUIZ FERNANDO DE ANDRADE PINTO,2024-12-28,None,APELAÇÃO CÍVEL. RELAÇÃO DE CONSUMO. TRANSAÇÕE...