# TJRN - Tribunal de Justica do Rio Grande do Norte

Jurisprudence scraper for TJRN, via Elasticsearch API.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |

In [6]:
import juscraper as jus

tjrn = jus.scraper('tjrn')

## Basic search

In [7]:
df = tjrn.cjsg('dano moral', paginas=range(1, 3))

print(df.shape)
df.head(3)

Baixando CJSG TJRN: 100%|██████████| 2/2 [00:03<00:00,  1.55s/it]

(20, 10)

,processo,classe_judicial,orgao_julgador,colegiado,relator,tipo_decisao,data_julgamento,ementa,sistema,sigiloso
0,0806044-02.2023.8.20.5001,APELAÇÃO CÍVEL,Gab. Des. Amilcar Maia na Câmara Cível,Terceira Câmara Cível,None,None,NaT,Ementa: DIREITO CIVIL E PROCESSUAL CIVIL. APEL...,PJE,False
1,0817054-63.2025.8.20.5004,RECURSO INOMINADO CÍVEL,Gab. do Juiz José Conrado Filho,2ª Turma Recursal,None,None,NaT,PODER JUDICIÁRIO DO ESTADO DO RIO GRANDE DO NO...,PJE,False
2,0801742-84.2024.8.20.5100,APELAÇÃO CÍVEL,Gab. Des. Amilcar Maia na Câmara Cível,Terceira Câmara Cível,None,None,NaT,Normal 0 21 false false false PT-BR EMENTA : A...,PJE,False

## Available columns

In [8]:
brutos = tjrn.cjsg_download('dano moral', paginas=1)
df_parsed = tjrn.cjsg_parse(brutos)

print(df_parsed.shape)
df_parsed.head(3)

Baixando CJSG TJRN: 100%|██████████| 1/1 [00:01<00:00,  1.43s/it]

(10, 10)

,processo,classe_judicial,orgao_julgador,colegiado,relator,tipo_decisao,data_julgamento,ementa,sistema,sigiloso
0,0806044-02.2023.8.20.5001,APELAÇÃO CÍVEL,Gab. Des. Amilcar Maia na Câmara Cível,Terceira Câmara Cível,None,None,NaT,Ementa: DIREITO CIVIL E PROCESSUAL CIVIL. APEL...,PJE,False
1,0817054-63.2025.8.20.5004,RECURSO INOMINADO CÍVEL,Gab. do Juiz José Conrado Filho,2ª Turma Recursal,None,None,NaT,PODER JUDICIÁRIO DO ESTADO DO RIO GRANDE DO NO...,PJE,False
2,0801742-84.2024.8.20.5100,APELAÇÃO CÍVEL,Gab. Des. Amilcar Maia na Câmara Cível,Terceira Câmara Cível,None,None,NaT,Normal 0 21 false false false PT-BR EMENTA : A...,PJE,False

## Preview ementa

In [9]:
print(df['ementa'].iloc[0][:300])

Ementa: DIREITO CIVIL E PROCESSUAL CIVIL. APELAÇÃO CÍVEL. RESPONSABILIDADE CIVIL DE ADVOGADO. FALHA NA PRESTAÇÃO DE SERVIÇOS ADVOCATÍCIOS. DANO MORAL CONFIGURADO. PEDIDO SUBSIDIÁRIO DE REDUÇÃO DO QUANTUM INDENIZATÓRIO ACOLHIDO. RECURSO PARCIALMENTE PROVIDO. I. CASO EM EXAME Apelação cível interposta

## Using filters

Available filters: `nr_processo`, `id_classe_judicial`, `id_orgao_julgador`, `id_relator`, `id_colegiado`, `sistema` (PJE/SAJ), `decisoes`, `jurisdicoes`, `grau`.

In [10]:
df_filtered = tjrn.cjsg(
    'direito',
    data_inicio='2024-01-01',
    data_fim='2024-06-30',
    paginas=1,
)

print(df_filtered.shape)
df_filtered.head(3)

Baixando CJSG TJRN: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]

(10, 10)

,processo,classe_judicial,orgao_julgador,colegiado,relator,tipo_decisao,data_julgamento,ementa,sistema,sigiloso
0,0800929-73.2023.8.20.5106,APELAÇÃO CÍVEL,Gab. Des. Claudio Santos na Câmara Cível,Primeira Câmara Cível,None,None,NaT,EMENTA : DIREITO CIVIL E CONSUMIDOR. APELAÇÃO ...,PJE,False
1,0805644-19.2024.8.20.0000,CONFLITO DE COMPETÊNCIA CÍVEL,Gab. Des. Lourdes de Azevedo no Pleno,Tribunal Pleno,None,None,NaT,Normal 0 21 false false false PT-BR X-NONE X-N...,PJE,False
2,0824603-17.2022.8.20.5106,APELAÇÃO CÍVEL,Gab. Des. Claudio Santos na Câmara Cível,Primeira Câmara Cível,None,None,NaT,Normal 0 21 false false false PT-BR EMENTA : D...,PJE,False