# TJRR - Tribunal de Justica de Roraima

Jurisprudence scraper for TJRR, via JSF/PrimeFaces with ViewState management.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |

In [6]:
import juscraper as jus

tjrr = jus.scraper('tjrr')

## Basic search

In [7]:
df = tjrr.cjsg('dano moral', paginas=range(1,3))

print(df.shape)
df.head(3)

Baixando CJSG TJRR: 100%|██████████| 2/2 [00:06<00:00,  3.02s/it]

(30, 7)

,processo,classe,relator,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0827862-90.2025.8.23.0010,RI - Recurso Inominado,BRUNO FERNANDO ALVES COSTA,Turma Recursal,2026-03-30,2026-04-07,DIREITO DO CONSUMIDOR. RECURSO INOMINADO. SIST...
1,0817102-82.2025.8.23.0010,RI - Recurso Inominado,BRUNO FERNANDO ALVES COSTA,Turma Recursal,2026-03-30,2026-04-07,DIREITO CIVIL E DO CONSUMIDOR. RECURSO INOMINA...
2,0833332-15.2019.8.23.0010,ACr - Apelação Criminal,LUIZ FERNANDO MALLET,Câmara Criminal,2026-03-27,2026-04-06,DIREITO PENAL E PROCESSUAL PENAL. APELAÇÃO CRI...

## Available columns

In [8]:
brutos = tjrr.cjsg_download('dano moral', paginas=1)
df_parsed = tjrr.cjsg_parse(brutos)

print(df_parsed.shape)
df_parsed.head(3)

Baixando CJSG TJRR: 100%|██████████| 1/1 [00:00<?, ?it/s]

(20, 7)

,processo,classe,relator,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0827862-90.2025.8.23.0010,RI - Recurso Inominado,BRUNO FERNANDO ALVES COSTA,Turma Recursal,2026-03-30,2026-04-07,DIREITO DO CONSUMIDOR. RECURSO INOMINADO. SIST...
1,0817102-82.2025.8.23.0010,RI - Recurso Inominado,BRUNO FERNANDO ALVES COSTA,Turma Recursal,2026-03-30,2026-04-07,DIREITO CIVIL E DO CONSUMIDOR. RECURSO INOMINA...
2,0833332-15.2019.8.23.0010,ACr - Apelação Criminal,LUIZ FERNANDO MALLET,Câmara Criminal,2026-03-27,2026-04-06,DIREITO PENAL E PROCESSUAL PENAL. APELAÇÃO CRI...

## Preview ementa

In [9]:
print(df['ementa'].iloc[0][:300])

DIREITO DO CONSUMIDOR. RECURSO INOMINADO. SISTEMA DE INFORMAÇÕES DE CRÉDITO – SCR/SISBACEN. REGISTRO DE OPERAÇÃO BAIXADA COMO PREJUÍZO. DÍVIDA QUITADA POR ACORDO COM DESÁGIO. NATUREZA TÉCNICO-REGULATÓRIA DO SCR. DEVER DE REPORTE DA INSTITUIÇÃO FINANCEIRA. AUSÊNCIA DE ATO ILÍCITO. INEXISTÊNCIA DEDANO

## Using filters

Available filters: `relator`, `orgao_julgador` (list of codes), `especie` (list of resource types).

In [10]:
df_filtered = tjrr.cjsg(
    'direito',
    data_inicio='2024-01-01',
    data_fim='2024-06-30',
    paginas=1,
)

print(df_filtered.shape)
df_filtered.head(3)

Baixando CJSG TJRR: 100%|██████████| 1/1 [00:00<?, ?it/s]

(20, 7)

,processo,classe,relator,orgao_julgador,data_julgamento,data_publicacao,ementa
0,0827862-90.2025.8.23.0010,RI - Recurso Inominado,BRUNO FERNANDO ALVES COSTA,Turma Recursal,2026-03-30,2026-04-07,DIREITO DO CONSUMIDOR. RECURSO INOMINADO. SIST...
1,0817102-82.2025.8.23.0010,RI - Recurso Inominado,BRUNO FERNANDO ALVES COSTA,Turma Recursal,2026-03-30,2026-04-07,DIREITO CIVIL E DO CONSUMIDOR. RECURSO INOMINA...
2,0833332-15.2019.8.23.0010,ACr - Apelação Criminal,LUIZ FERNANDO MALLET,Câmara Criminal,2026-03-27,2026-04-06,DIREITO PENAL E PROCESSUAL PENAL. APELAÇÃO CRI...