# TJSC - Tribunal de Justica de Santa Catarina

Jurisprudence scraper for TJSC, via the eproc PHP system.

| Feature | Available |
|---------|----------|
| cjsg    | Yes      |

In [6]:
import juscraper as jus

tjsc = jus.scraper('tjsc')

## Basic search

In [7]:
df = tjsc.cjsg('dano moral', paginas=range(1, 3))

print(df.shape)
df.head(3)

Baixando CJSG TJSC: 100%|██████████| 2/2 [00:03<00:00,  1.71s/it]

(20, 8)

,processo,classe,orgao_julgador,relator,data_julgamento,data_publicacao,ementa,uf
0,5042483-02.2020.8.24.0038/TJSC,NaN,1ª Câmara Especial de Enfrentamento de Acervos,PATRÍCIA NOLLI,2026-04-08,2026-04-08,DIREITO DO CONSUMIDOR. APELAÇÕES CÍVEIS. AÇÃO ...,SC
1,5003931-18.2023.8.24.0052/TJSC,NaN,6ª Câmara de Direito Civil,QUITERIA TAMANINI VIEIRA,2026-04-08,2026-04-08,DIREITO CIVIL E DO CONSUMIDOR. AÇÃO DECLARATÓR...,SC
2,5048640-54.2021.8.24.0038/TJSC,NaN,6ª Câmara de Direito Civil,QUITERIA TAMANINI VIEIRA,2026-04-08,2026-04-08,DIREITO CIVIL E PROCESSUAL CIVIL. EMBARGOS DE ...,SC

## Available columns

In [8]:
brutos = tjsc.cjsg_download('dano moral', paginas=1)
df_parsed = tjsc.cjsg_parse(brutos)

print(df_parsed.shape)
df_parsed.head(3)

Baixando CJSG TJSC: 100%|██████████| 1/1 [00:01<00:00,  1.50s/it]

(10, 8)

,processo,classe,orgao_julgador,relator,data_julgamento,data_publicacao,ementa,uf
0,0302139-45.2014.8.24.0282/TJSC,NaN,3ª Câmara de Direito Civil,ANTONIO AUGUSTO BAGGIO E UBALDO,2026-04-08,2026-04-08,APELAÇÃO CÍVEL. AÇÃO INDENIZATÓRIA POR SUPOSTA...,SC
1,5000076-73.2024.8.24.0059/TJSC,NaN,3ª Câmara de Direito Civil,ANTONIO AUGUSTO BAGGIO E UBALDO,2026-04-08,2026-04-08,APELAÇÃO CÍVEL. AÇÃO DECLARATÓRIA DE NULIDADE ...,SC
2,5029071-60.2021.8.24.0008/TJSC,NaN,3ª Câmara de Direito Civil,ANTONIO AUGUSTO BAGGIO E UBALDO,2026-04-08,2026-04-08,APELAÇÃO CÍVEL. AÇÃO DECLARATÓRIA DE NULIDADE ...,SC

## Preview ementa

In [9]:
if 'ementa' in df.columns and len(df) > 0:
    print(df['ementa'].iloc[0][:300])

DIREITO DO CONSUMIDOR. APELAÇÕES CÍVEIS. AÇÃO DE INDENIZAÇÃO POR DANOS MATERIAIS E MORAIS. VEÍCULO AUTOMOTOR SUBMETIDO A REPAROS APÓS SINISTRO. DEMORA NA CONCLUSÃO DO SERVIÇO E FALHA NO DEVER DE INFORMAÇÃO.DANOMORALCONFIGURADO. SENTENÇA DE PARCIAL PROCEDÊNCIA. INTEMPESTIVIDADE DO APELO DO AUTOR. NÃO

## Using filters

Available filters: `campo` (E=ementa, I=inteiro teor), `processo`, `data_decisao_inicio/fim`, `data_publicacao_inicio/fim`.

In [10]:
df_filtered = tjsc.cjsg(
    'direito',
    campo='E',
    paginas=1,
)

print(df_filtered.shape)
df_filtered.head(3)

Baixando CJSG TJSC: 100%|██████████| 1/1 [00:01<00:00,  1.67s/it]

(10, 8)

,processo,classe,orgao_julgador,relator,data_julgamento,data_publicacao,ementa,uf
0,5042483-02.2020.8.24.0038/TJSC,NaN,1ª Câmara Especial de Enfrentamento de Acervos,PATRÍCIA NOLLI,2026-04-08,2026-04-08,DIREITODO CONSUMIDOR. APELAÇÕES CÍVEIS. AÇÃO D...,SC
1,5005007-27.2023.8.24.0004/TJSC,NaN,1ª Câmara Especial de Enfrentamento de Acervos,PATRÍCIA NOLLI,2026-04-08,2026-04-08,DIREITOCIVIL. APELAÇÕES CÍVEIS. AÇÃO DE COBRAN...,SC
2,5002184-70.2023.8.24.0072/TJSC,NaN,1ª Câmara Especial de Enfrentamento de Acervos,PATRÍCIA NOLLI,2026-04-08,2026-04-08,DIREITOPROCESSUAL CIVIL E CIVIL. EMBARGOS DE D...,SC