# JusScraper - Tribunal de Justiça de São Paulo (TJSP)

Este notebook demonstra como usar o `juscraper` para extrair dados do Tribunal de Justiça de São Paulo (TJSP). O pacote oferece acesso programático a várias consultas disponíveis no sistema ESAJ do TJSP.

## Funcionalidades Disponíveis

O `juscraper` para TJSP oferece acesso a:

- **CJPG**: Consulta de Julgados de Primeiro Grau
- **CJSG**: Consulta de Julgados de Segundo Grau  
- **CPOPG**: Consulta Processual de Primeiro Grau
- **CPOSG**: Consulta Processual de Segundo Grau

## Instalação e Importação

Primeiro, vamos importar o pacote e criar um objeto scraper para o TJSP:

In [1]:
import juscraper as jus

# cria um objeto tjsp
tjsp = jus.scraper('tjsp')

## Criando o Scraper

Para começar a usar o `juscraper` com o TJSP, você precisa criar uma instância do scraper passando `'tjsp'` como argumento. Este objeto será usado para todas as consultas subsequentes.

## CJPG - Consulta de Julgados de Primeiro Grau

A função `cjpg()` permite buscar decisões e sentenças proferidas em primeiro grau de jurisdição. É útil para encontrar precedentes, entender padrões de julgamento ou coletar dados para análise jurídica.

### Parâmetros Principais

- `pesquisa` (str): Termo de busca que será pesquisado no conteúdo das decisões
- `paginas` (int | range | list | None): Número de páginas a serem baixadas (1-based). Use `paginas=n` para baixar as primeiras `n` páginas, ou `range(1, n+1)` para o mesmo efeito. Default `None` baixa todas as páginas.
- `classes` (list, opcional): Lista de códigos de classes processuais para filtrar
- `assuntos` (list, opcional): Lista de códigos de assuntos para filtrar
- `varas` (list, opcional): Lista de códigos de varas para filtrar

### Retorno

A função retorna um `pandas.DataFrame` com as seguintes colunas principais:
- `cd_processo`: Código interno do processo
- `id_processo`: Número do processo (formato CNJ)
- `classe`: Classe processual
- `assunto`: Assunto do processo
- `magistrado`: Nome do magistrado que proferiu a decisão
- `comarca`: Comarca onde o processo tramitou
- `foro`: Foro onde o processo tramitou
- `vara`: Vara onde o processo tramitou
- `data_disponibilizacao`: Data em que a decisão foi disponibilizada
- `decisao`: Texto completo da decisão/sentença

### Exemplo de Uso

In [2]:
# baixa dados da [c]onsulta de [j]ulgados de [p]rimeiro [g]rau - cjpg
dados_cjpg = tjsp.cjpg('golpe do pix', paginas=3)

print(dados_cjpg.shape)
dados_cjpg.head(3)

Baixando documentos:  33%|███▎      | 1/3 [00:00<?, ?it/s]

Baixando documentos:  67%|██████▋   | 2/3 [00:00<00:00,  1.43it/s]

Baixando documentos: 100%|██████████| 3/3 [00:01<00:00,  1.13it/s]

Baixando documentos: 100%|██████████| 3/3 [00:01<00:00,  1.16it/s]

Processando documentos:   0%|          | 0/3 [00:00<?, ?it/s]

Processando documentos: 100%|██████████| 3/3 [00:00<00:00, 34.92it/s]

(30, 10)

,cd_processo,id_processo,classe,assunto,magistrado,comarca,foro,vara,data_disponibilizacao,decisao
0,F20001K5M0000,1504525-71.2023.8.26.0542,Ação Penal - Procedimento Ordinário,Estelionato,FILIPPO DEL GIUDICE GAROFALO,Cesário Lange,Foro de Cesário Lange,Vara Única,05/03/2026,SENTENÇA\n\nProcesso Digital nº:\t1504525-71.2...
1,G1000RD980000,1514283-32.2024.8.26.0577,Procedimento Comum Cível,"Defeito, nulidade ou anulação",Maurício Brisque Neiva,São José dos Campos,Foro de São José dos Campos,1ª Vara Cível,05/03/2026,SENTENÇA\nProcesso nº:\t1514283-32.2024.8.26.0...
2,E2000T1G40000,1508308-48.2024.8.26.0506,Ação Penal - Procedimento Ordinário,Estelionato,Vanessa Aparecida Pereira Barbosa,Ribeirão Preto,Foro de Ribeirão Preto,4ª Vara Criminal,05/03/2026,SENTENÇA\n\nProcesso Digital nº:\t1508308-48.2...

## CJSG - Consulta de Julgados de Segundo Grau

A função `cjsg()` permite buscar acórdãos e decisões monocráticas proferidas pelos tribunais de segundo grau. Esta é uma das consultas mais utilizadas para pesquisa jurisprudencial.

### Parâmetros Principais

- `pesquisa` (str): Termo de busca que será pesquisado no conteúdo das decisões e ementas
- `paginas` (int | range | list | None): Número de páginas a serem baixadas (1-based). Use `paginas=n` para baixar as primeiras `n` páginas, ou `range(1, n+1)` para o mesmo efeito. Default `None` baixa todas as páginas.
- `ementa` (str, opcional): Termo adicional para buscar especificamente nas ementas
- `classe` (str, opcional): Código da classe processual
- `assunto` (str, opcional): Código do assunto
- `comarca` (str, opcional): Código da comarca
- `orgao_julgador` (str, opcional): Código do órgão julgador
- `data_julgamento_inicio` (str, opcional): Data inicial de julgamento (formato: DD/MM/AAAA)
- `data_julgamento_fim` (str, opcional): Data final de julgamento (formato: DD/MM/AAAA)
- `baixar_sg` (bool, opcional): Se `True` (padrão), busca em segundo grau. Se `False`, busca em colégio recursal
- `tipo_decisao` (str, opcional): Tipo de decisão - `'acordao'` (padrão) ou `'monocratica'`

### Retorno

A função retorna um `pandas.DataFrame` com as seguintes colunas principais:
- `processo`: Número do processo (formato CNJ)
- `cd_acordao`: Código interno do acórdão
- `cd_foro`: Código do foro
- `classe_assunto`: Classe processual e assunto combinados
- `relatora`: Nome do relator
- `comarca`: Comarca de origem
- `orgao_julgador`: Órgão julgador (ex: "13ª Câmara de Direito Privado")
- `data_julgamento`: Data do julgamento
- `data_publicacao`: Data de publicação
- `ementa`: Texto da ementa do acórdão

### Exemplo de Uso

In [3]:
# baixa dados da [c]onsulta de [j]ulgados de [s]egundo [g]rau - cjsg
dados_cjsg = tjsp.cjsg('golpe do pix', paginas=3)

print(dados_cjsg.shape)
dados_cjsg.head(3)

Baixando documentos:  33%|███▎      | 1/3 [00:00<?, ?it/s]

Baixando documentos:  67%|██████▋   | 2/3 [00:01<00:01,  1.07s/it]

Baixando documentos: 100%|██████████| 3/3 [00:01<00:00,  1.07it/s]

Baixando documentos: 100%|██████████| 3/3 [00:01<00:00,  1.05it/s]

Processando documentos:   0%|          | 0/3 [00:00<?, ?it/s]

Processando documentos: 100%|██████████| 3/3 [00:00<00:00, 32.05it/s]

(60, 10)

,processo,cd_acordao,cd_foro,classe_assunto,relatora,comarca,orgao_julgador,data_julgamento,data_publicacao,ementa
0,1032449-14.2024.8.26.0564,20239033,0,Apelação Cível / Cartão de Crédito,M.A. Barbosa de Freitas,São Bernardo do Campo,Núcleo de Justiça 4.0 em Segundo Grau – Turma ...,05/03/2026,05/03/2026,APELAÇÃO DO AUTOR – REPETIÇÃO DO INDÉBITO E PR...
1,1004637-16.2025.8.26.0223,20238927,0,Apelação Cível / Bancários,Fernando Sastre Redondo,Guarujá,38ª Câmara de Direito Privado,05/03/2026,05/03/2026,"AÇÃO DE REPARAÇÃO DE DANOS. "" Golpe do falso a..."
2,1000648-61.2024.8.26.0247,20239053,0,Embargos de Declaração Cível / Bancários,Inah de Lemos e Silva Machado,Ilhabela,Núcleo de Justiça 4.0 em Segundo Grau – Turma ...,05/03/2026,05/03/2026,EMBARGOS DE DECLARAÇÃO. EMPRÉSTIMO PESSOAL E T...

## CPOPG - Consulta Processual de Primeiro Grau

A função `cpopg()` permite consultar informações detalhadas sobre processos em primeiro grau de jurisdição. Diferente das consultas de julgados, esta função retorna informações processuais completas, incluindo partes, movimentações, petições e documentos.

### Parâmetros Principais

- `id_processo` (str): Número do processo no formato CNJ (ex: "1000149-71.2024.8.26.0346")

### Retorno

A função retorna um dicionário Python com as seguintes chaves:

- `basicos`: DataFrame com informações básicas do processo (classe, assunto, foro, vara, juiz, data de distribuição, valor da ação)
- `partes`: DataFrame com informações das partes (requerente, requerido, advogados)
- `movimentacoes`: DataFrame com histórico de movimentações do processo (data, movimento, observação)
- `peticoes_diversas`: DataFrame com informações sobre petições e documentos protocolados

### Exemplo de Uso

In [4]:
res = tjsp.cpopg('1000149-71.2024.8.26.0346')
res

Baixando processos:   0%|          | 0/1 [00:00<?, ?it/s]

Baixando processos: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s]

Baixando processos: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s]

Processando documentos:   0%|          | 0/1 [00:00<?, ?it/s]

Processando documentos: 100%|██████████| 1/1 [00:00<00:00, 29.56it/s]

{'basicos':                                            file_path  \
 0  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...

                  id_processo                    classe  \
 0  1000149-71.2024.8.26.0346  Procedimento Comum Cível

                           assunto                  foro               vara  \
 0  Responsabilidade do Fornecedor  Foro de Martinópolis  2ª  Vara Judicial

                     juiz            data_distribuicao            valor_acao
 0  RENATA ESSER DE SOUZA  06/02/2024 às 13:47 - Livre  R$         81.439,78  ,
 'partes':                                            file_path       tipo  \
 0  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...      Reqte
 1  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...      Reqda
 2  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  TerIntCer

                                                 nome  \
 0  Aparecida Stuani Advogada: Carina Akemi Rezend...
 1                                BANCO BRADESCO S.A.
 2                   Canavarro Campos Mello Advogados

                                    advogados
 0  [Fabio Cabral Silva de Oliveira Monteiro]
 1  [Fabio Cabral Silva de Oliveira Monteiro]
 2                                         []  ,
 'movimentacoes':                                              file_path        data  \
 0    /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  02/03/2026
 1    /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  02/03/2026
 2    /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  27/02/2026
 3    /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  27/02/2026
 4    /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  27/02/2026
 ..                                                 ...         ...
 109  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  09/02/2024
 110  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  09/02/2024
 111  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  08/02/2024
 112  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  07/02/2024
 113  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  06/02/2024

                                              movimento  \
 0
 1                      Certidão de Publicação Expedida
 2                                      Remetido ao DJE
 3
 4                              Conclusos para Despacho
 ..                                                 ...
 109                    Certidão de Publicação Expedida
 110                                    Remetido ao DJE
 111
 112                             Conclusos para Decisão
 113  Distribuído Livremente (por Sorteio) (moviment...

                                             observacao
 0                              Certidão - expedido MLE
 1    Relação: 0271/2026\nData da Publicação: 03/03/...
 2    Relação: 0271/2026\nTeor do ato: 1. Expeça-se ...
 3    1. Expeça-se mandado de levantamento em favor ...
 4
 ..                                                 ...
 109  Relação: 0055/2024\nData da Publicação: 15/02/...
 110  Relação: 0055/2024\nTeor do ato: Vistos. O art...
 111  Vistos. O artigo 5º, LXXIV, da Constituição Fe...
 112
 113

 [114 rows x 4 columns],
 'peticoes_diversas':                                             file_path        data  \
 0   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...
 1   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  14/02/2024
 2   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  19/03/2024
 3   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  21/03/2024
 4   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  10/04/2024
 5   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  23/04/2024
 6   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  25/04/2024
 7   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  25/04/2024
 8   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  29/04/2024
 9   /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  03/05/2024
 10  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  10/06/2024
 11  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  23/07/2024
 12  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  13/08/2024
 13  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  14/08/2024
 14  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  28/08/2024
 15  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  29/08/2024
 16  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  02/09/2024
 17  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  04/09/2024
 18  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  07/10/2024
 19  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  16/10/2024
 20  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  22/10/2024
 21  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  04/12/2024
 22  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  14/10/2025
 23  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  23/10/2025
 24  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  29/10/2025
 25  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  23/02/2026
 26  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  23/02/2026
 27  /tmp/tmpow3ic72x/cpopg/10001497120248260346/10...  26/02/2026

                                               tipo
 0
 1                                 Emenda à Inicial
 2                                      Contestação
 3                    Pedido de Expedição de Ofício
 4                            Petição Intermediária
 5                                      Contestação
 6                                Petições Diversas
 7                                      Contestação
 8                                      Contestação
 9                                      Contestação
 10                           Pedido de Habilitação
 11                               Petições Diversas
 12                           Petição Intermediária
 13                             Indicação de Provas
 14                               Petições Diversas
 15                             Indicação de Provas
 16                               Petições Diversas
 17                               Petições Diversas
 18                           Petição Intermediária
 19                           Pedido de Habilitação
 20                              Razões de Apelação
 21                       Contrarrazões de Apelação
 22                  Pedido de Extinção do Processo
 23                           Petição Intermediária
 24  Pedido de Expedição de Mandado de Levantamento
 25                           Petição Intermediária
 26                               Petições Diversas
 27                           Petição Intermediária  }

## CPOSG - Consulta Processual de Segundo Grau

A função `cposg()` permite consultar informações detalhadas sobre processos em segundo grau de jurisdição (recursos). Esta função retorna informações completas sobre o processo em segundo grau, incluindo composição do colegiado, decisões, movimentações e histórico.

### Parâmetros Principais

- `id_processo` (str ou list): Número(s) do processo no formato CNJ. Pode ser uma string única ou uma lista de strings para consultar múltiplos processos de uma vez.

### Retorno

A função retorna um `pandas.DataFrame` onde cada linha representa um processo consultado. As colunas principais incluem:

- `id_original`: ID original do processo
- `status`: Status atual do processo (ex: "Encerrado", "Em andamento")
- `classe`: Classe processual
- `assunto`: Assunto do processo
- `secao`: Seção do tribunal
- `orgao_julgador`: Órgão julgador responsável
- `area`: Área do direito (Cível, Criminal, etc.)
- `relator`: Nome do relator
- `origem`: Informações sobre a origem (comarca, foro, vara de primeiro grau)
- `movimentacoes`: Lista de dicionários com movimentações do processo
- `partes`: Lista de dicionários com informações das partes
- `historico`: Histórico do processo
- `decisoes`: Lista de decisões proferidas
- `composicao`: Informações sobre a composição do colegiado
- `primeira_inst`: Informações sobre o processo de primeira instância
- `processo`: Número do processo
- `valor_da_acao`: Valor da ação (se aplicável)
- `volume_apenso`: Informações sobre volumes apensos

### Exemplo de Uso

Você pode consultar um único processo ou múltiplos processos de uma vez:

In [5]:
res = tjsp.cposg(['00221752420038260344', '10001497120248260346', '00039417120248260048'])
res

Baixando processos:   0%|          | 0/3 [00:00<?, ?it/s]

Baixando processos:  33%|███▎      | 1/3 [00:01<00:02,  1.31s/it]

Baixando processos:  67%|██████▋   | 2/3 [00:02<00:01,  1.08s/it]

Baixando processos: 100%|██████████| 3/3 [00:03<00:00,  1.05it/s]

Baixando processos: 100%|██████████| 3/3 [00:03<00:00,  1.01s/it]

Processando arquivos:   0%|          | 0/4 [00:00<?, ?it/s]

Processando arquivos: 100%|██████████| 4/4 [00:00<00:00, 24.03it/s]

Processando arquivos: 100%|██████████| 4/4 [00:00<00:00, 23.92it/s]

,id_original,status,classe,assunto,secao,orgao_julgador,area,relator,valor_da_acao,origem,movimentacoes,partes,historico,decisoes,composicao,primeira_inst,processo,volume_apenso
0,1000149-71.2024.8.26.0346,Encerrado,Apelação Cível,DIREITO DO CONSUMIDOR - Contratos de Consumo -...,Direito Privado 2,Núcleo de Justiça 4.0 em Segundo Grau – Turma ...,Cível,PAULO SERGIO MANGERONA,"72.896,87",Comarca de Martinópolis / Foro de Martinópolis...,"[{'data': '25/06/2025', 'movimento': 'Expedido...","[{'id_parte': 1, 'nome': 'Fabio Cabral Silva d...",[],"[{'data': '24/05/2025', 'situacao': 'Julgado',...","[{'participacao': 'Relator', 'magistrado': 'Pa...",[{'id_1a_inst': '1000149-71.2024.8.26.0346(Pri...,None,None
1,Embargos de Declaração Criminal\n\t\t\n\t\t\t ...,Encerrado,Apelação Criminal,DIREITO PENAL-Crimes contra a vida-Homicídio S...,Direito Criminal,6ª Câmara de Direito Criminal,Criminal,MACHADO DE ANDRADE,None,Comarca de Marília / Foro de Marília / 1ª Vara...,"[{'data': '25/07/2022', 'movimento': 'Informaç...","[{'id_parte': 1, 'nome': 'Rubens Neres Santana...",[],"[{'data': '01/08/2019', 'situacao': 'Julgado',...","[{'participacao': 'Relator', 'magistrado': 'Ma...","[{'id_1a_inst': '344.01.2003.022175-3', 'foro'...",None,None
2,Embargos de Declaração Criminal\n\t\t\n\t\t\t ...,Encerrado,Recurso em Sentido Estrito,DIREITO PENAL - Crime Tentado,Direito Criminal,16ª Câmara de Direito Criminal,Criminal,BORGES PEREIRA,None,Comarca de Marília / Foro de Marília / 3ª. Var...,"[{'data': '25/03/2015', 'movimento': 'Decisão ...","[{'id_parte': 1, 'nome': 'Jose Roberto dos Rei...",[],"[{'data': '20/03/2012', 'situacao': 'Julgado',...","[{'participacao': 'Relator', 'magistrado': 'Bo...","[{'id_1a_inst': '344.01.2003.022175-3', 'foro'...",None,None

In [6]:
import pandas as pd
pd.DataFrame(res['movimentacoes'].iloc[2]).head()

,data,movimento,descricao
0,25/03/2015,Decisão Monocrática - Não Provida,ofício remetido à v.o.
1,08/11/2013,Remetidos os Autos para Vara de Origem,
2,08/11/2013,Recebidos os Autos do STJ pelo Processamento d...,
3,08/11/2013,Remetidos os Autos para Processamento de Recur...,
4,21/10/2013,Publicado em,Disponibilizado em 18/10/2013\nTipo de publica...

### Trabalhando com Dados Estruturados

Os dados retornados por `cposg()` contêm informações aninhadas (listas de dicionários) em algumas colunas. Você pode facilmente converter essas informações em DataFrames separados para análise mais detalhada.

Por exemplo, para trabalhar com as movimentações de um processo específico:

## Dicas e Observações Importantes

### Performance e Limites

- **Rate Limiting**: O sistema ESAJ pode ter limites de requisições. Use `sleep_time` no construtor do scraper para adicionar delays entre requisições se necessário.
- **Páginas**: Use o parâmetro `paginas` com cuidado. Baixar muitas páginas pode levar muito tempo e sobrecarregar o servidor.
- **Dados Temporários**: Por padrão, os arquivos HTML baixados são salvos em um diretório temporário e removidos após o parse. Para manter os arquivos, use `cjsg_download()` ou `cjpg_download()` separadamente.

### Formato de Datas

Todas as datas retornadas estão no formato brasileiro: **DD/MM/AAAA**.

### Formato de Processos

Os números de processo devem estar no formato CNJ completo: **NNNNNNN-DD.AAAA.J.TR.OOOO** (ex: "1000149-71.2024.8.26.0346").

### Tratamento de Erros

- Se uma busca não retornar resultados, a função retornará um DataFrame vazio.
- Se houver problemas de conexão ou o servidor estiver indisponível, uma exceção será levantada.
- Para consultas processuais (`cpopg` e `cposg`), processos não encontrados podem retornar dados parciais ou vazios.