# TJTO - Tribunal de Justica do Estado do Tocantins

Scraper for the jurisprudence search of TJTO.

| Feature | Status |
|---------|--------|
| cjsg (Acordaos - 2nd instance) | Supported |
| cjsg (Decisoes Monocraticas - 2nd instance) | Supported |
| cjpg (Sentencas - 1st instance) | Supported |
| cpopg | Not implemented |
| cposg | Not implemented |

## Basic search (2nd instance)

In [1]:
import juscraper as jus

tjto = jus.scraper('tjto')

dados_cjsg = tjto.cjsg('dano moral', paginas=range(1, 3))
print(dados_cjsg.shape)
dados_cjsg.head(3)

Baixando páginas TJTO: 100%|██████████| 2/2 [00:03<00:00,  1.71s/it]

(40, 10)

,processo,uuid,classe,tipo_julgamento,assunto,competencia,relator,data_autuacao,data_julgamento,processo_link
0,0002656-14.2020.8.27.2713,f3ec3d1a4de006daf1b9dfd61c152156,Apelação Cível,Agravo Interno,"PASEP, Contribuições Sociais, Contribuições, D...",TURMAS DAS CAMARAS CIVEIS,JACQUELINE ADORNO DE LA CRUZ BARBOSA,2020-08-24,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...
1,0016145-84.2025.8.27.2700,c4ad73c51323aab98cf079d95b6fb036,Mandado de Segurança Cível,Mérito,Progressão Funcional com Interstício de Doze M...,TRIBUNAL PLENO,MARIA CELMA LOUZEIRO TIAGO,2025-10-09,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...
2,0015935-33.2025.8.27.2700,37c2e4ffc3a32766a616b07f6829410c,Mandado de Segurança Cível,Mérito,"Ingresso e Concurso, Regime, Militar, DIREITO ...",TRIBUNAL PLENO,LUIZ ZILMAR DOS SANTOS PIRES,2025-10-07,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...

## Available columns

In [2]:
dados_cjsg.columns.tolist()

['processo',
 'uuid',
 'classe',
 'tipo_julgamento',
 'assunto',
 'competencia',
 'relator',
 'data_autuacao',
 'data_julgamento',
 'processo_link']

## Preview result fields

In [3]:
row = dados_cjsg.iloc[0]
print(f"Processo: {row['processo']}")
print(f"Classe: {row['classe']}")
print(f"Relator: {row['relator']}")
print(f"Competencia: {row['competencia']}")
print(f"Data Julgamento: {row['data_julgamento']}")

Processo: 0002656-14.2020.8.27.2713
Classe: Apelação Cível
Relator: JACQUELINE ADORNO DE LA CRUZ BARBOSA
Competencia: TURMAS DAS CAMARAS CIVEIS
Data Julgamento: 2026-03-26

## Using filters

You can filter by judgment date range and sort order.

In [4]:
dados_filtrados = tjto.cjsg(
    'direito',
    paginas=range(1, 3),
    data_julgamento_inicio='01/01/2025',
    data_julgamento_fim='30/06/2025',
)
print(dados_filtrados.shape)
dados_filtrados.head(3)

Baixando páginas TJTO: 100%|██████████| 2/2 [00:02<00:00,  1.46s/it]

(40, 10)

,processo,uuid,classe,tipo_julgamento,assunto,competencia,relator,data_autuacao,data_julgamento,processo_link
0,0019143-25.2025.8.27.2700,28e5df23dc2e2c72911c210a6f7f4a72,Revisão Criminal,Mérito,"Tráfico de Drogas e Condutas Afins, Crimes de ...",TRIBUNAL PLENO,SILVANA MARIA PARFIENIUK,2025-11-28,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...
1,0020000-08.2024.8.27.2700,1efbf3958a57ce39eb3fcd14bad83ce9,Revisão Criminal,Embargos de Declaração,"Homicídio Qualificado, Crimes contra a vida, D...",TRIBUNAL PLENO,SILVANA MARIA PARFIENIUK,2024-11-28,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...
2,0017052-59.2025.8.27.2700,93f9f65bd4e89cb0fa0cfda3744b5db6,Revisão Criminal,Mérito,"Crime Tentado, DIREITO PENAL",TRIBUNAL PLENO,SILVANA MARIA PARFIENIUK,2025-10-22,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...

## Querying different document types

Besides `acordaos` (default), you can also query `decisoes` (monocratic decisions) and `sentencas` (sentences).

In [5]:
dados_decisoes = tjto.cjsg('direito', paginas=range(1, 3), tipo_documento='decisoes')
print(dados_decisoes.shape)
dados_decisoes.head(3)

Baixando páginas TJTO: 100%|██████████| 2/2 [00:02<00:00,  1.26s/it]

(40, 10)

,processo,uuid,classe,tipo_julgamento,assunto,competencia,relator,data_autuacao,data_julgamento,processo_link
0,0006819-66.2026.8.27.2700,06f9d8f2d2e0170805a77a6213350b17,Habeas Corpus Cível,Decisão - Concessão - Liminar - Monocrático,"Alimentos, Prisão Civil, Liquidação / Cumprime...",CAMARAS DE DIREITO PÚBLICO,GIL DE ARAÚJO CORRÊA,2026-04-05,2026-04-05,https://eproc2.tjto.jus.br/consulta_publica/2G...
1,0006817-96.2026.8.27.2700,6b1b8c95df96b101366b0abbab02662d,Habeas Corpus Criminal,Decisão - Outras Decisões,"Liberdade Provisória, DIREITO PROCESSUAL PENAL...",CAMARAS CRIMINAIS,GIL DE ARAÚJO CORRÊA,2026-04-04,2026-04-05,https://eproc2.tjto.jus.br/consulta_publica/2G...
2,0006814-44.2026.8.27.2700,996cf26f0c2cd048c6781c307a506b69,Habeas Corpus Criminal,Decisão - Não-Concessão - Liminar - Monocrático,Crime de Descumprimento de Medida Protetiva de...,CAMARAS CRIMINAIS,GIL DE ARAÚJO CORRÊA,2026-04-04,2026-04-04,https://eproc2.tjto.jus.br/consulta_publica/2G...

## Download and parse separately

You can also download the raw HTML first and parse it later.

In [6]:
brutos = tjto.cjsg_download('direito', paginas=range(1, 3))
print(f"Pages downloaded: {len(brutos)}")
print(f"Raw HTML size (page 1): {len(brutos[0])} chars")

dados = tjto.cjsg_parse(brutos)
print(f"\nParsed shape: {dados.shape}")
dados.head(3)

Baixando páginas TJTO: 100%|██████████| 2/2 [00:02<00:00,  1.33s/it]

Pages downloaded: 2
Raw HTML size (page 1): 1123144 chars

Parsed shape: (40, 10)

,processo,uuid,classe,tipo_julgamento,assunto,competencia,relator,data_autuacao,data_julgamento,processo_link
0,0019143-25.2025.8.27.2700,28e5df23dc2e2c72911c210a6f7f4a72,Revisão Criminal,Mérito,"Tráfico de Drogas e Condutas Afins, Crimes de ...",TRIBUNAL PLENO,SILVANA MARIA PARFIENIUK,2025-11-28,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...
1,0020000-08.2024.8.27.2700,1efbf3958a57ce39eb3fcd14bad83ce9,Revisão Criminal,Embargos de Declaração,"Homicídio Qualificado, Crimes contra a vida, D...",TRIBUNAL PLENO,SILVANA MARIA PARFIENIUK,2024-11-28,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...
2,0017052-59.2025.8.27.2700,93f9f65bd4e89cb0fa0cfda3744b5db6,Revisão Criminal,Mérito,"Crime Tentado, DIREITO PENAL",TRIBUNAL PLENO,SILVANA MARIA PARFIENIUK,2025-10-22,2026-03-26,https://eproc2.tjto.jus.br/consulta_publica/2G...

## First instance search (cjpg)

Use `cjpg()` to search first-instance jurisprudence. It accepts the same parameters as `cjsg()`.

In [7]:
dados_cjpg = tjto.cjpg('dano moral', paginas=range(1, 3))
print(dados_cjpg.shape)
dados_cjpg.head(3)

Baixando páginas TJTO: 100%|██████████| 2/2 [00:03<00:00,  1.56s/it]

(40, 10)

,processo,uuid,classe,tipo_julgamento,assunto,competencia,relator,data_autuacao,data_julgamento,processo_link
0,0004882-39.2022.8.27.2707,1900caffbaab9b318e0b0696597593cd,Recurso Inominado Cível,Julgamento Principal,"Promoção / Ascensão, Regime Estatutário, Servi...",TURMAS RECURSAIS,,2022-12-07,2026-03-06,https://eproc1.tjto.jus.br/consulta_publica/1G...
1,0002068-17.2020.8.27.2742,b9ebc5c1e20bdb3bc8f865f56ef94b19,Recurso Inominado Cível,Julgamento Principal,"Empréstimo consignado, Bancários, Contratos de...",TURMAS RECURSAIS,,2020-01-23,2026-03-06,https://eproc1.tjto.jus.br/consulta_publica/1G...
2,0003604-57.2023.8.27.2710,7f937097e010e1f471dcd70ecb04e342,Recurso Inominado Cível,Julgamento Principal,"Práticas Abusivas, DIREITO DO CONSUMIDOR, Forn...",TURMAS RECURSAIS,,2023-08-08,2026-03-06,https://eproc1.tjto.jus.br/consulta_publica/1G...

### First instance with filters

In [8]:
dados_cjpg_sentencas = tjto.cjpg(
    'direito',
    paginas=range(1, 3),
    tipo_documento='sentencas',
)
print(dados_cjpg_sentencas.shape)
dados_cjpg_sentencas.head(3)

Baixando páginas TJTO: 100%|██████████| 2/2 [00:04<00:00,  2.50s/it]

(40, 10)

,processo,uuid,classe,tipo_julgamento,assunto,competencia,relator,data_autuacao,data_julgamento,processo_link
0,5000173-74.2011.8.27.2701,574a758833969a66da0792c68a50863c,Cumprimento de Sentença contra a Fazenda Pública,Julgamento - Com Resolução do Mérito - Extinçã...,"Pensão por Morte (Art. 74/9), Benefícios em Es...",CIVEL,,2011-06-03,2026-04-06,https://eproc1.tjto.jus.br/consulta_publica/1G...
1,0003673-96.2026.8.27.2706,5eda7d8e91adf2273bac02016cccc8cb,Procedimento do Juizado Especial Cível,Julgamento - Sem Resolução de Mérito - Extinçã...,"Perdas e Danos, Inadimplemento, Obrigações, DI...",JUIZADOS ESPECIAIS CÍVEIS,,2026-02-25,2026-04-06,https://eproc1.tjto.jus.br/consulta_publica/1G...
2,0051470-67.2024.8.27.2729,7377325b349c19526c0c5bda4acaa86b,Procedimento Comum Cível,Julgamento - Com Resolução do Mérito - Procedê...,"Exoneração, Alimentos, Família, DIREITO CIVIL",FAMÍLIA E SUCESSÕES,,2024-12-02,2026-04-06,https://eproc1.tjto.jus.br/consulta_publica/1G...