# TRF3 — Tribunal Regional Federal da 3ª Região

Public process consultation for the federal courts of the third region (SP
and MS), through the JSON API behind the PJe public consultation apps:
[pje1g-consultapublica.trf3.jus.br](https://pje1g-consultapublica.trf3.jus.br/)
(first instance, `cpopg`) and
[pje2g-consultapublica.trf3.jus.br](https://pje2g-consultapublica.trf3.jus.br/)
(appeals, `cposg`).

| Feature | Available |
|---------|-----------|
| cpopg   | Yes       |
| cposg   | Yes       |
| cjsg    | No        |
| cjpg    | No        |

## Looking up a single process

In [1]:
import juscraper as jus

trf3 = jus.scraper("trf3")

In [2]:
df = trf3.cpopg("5003536-21.2025.4.03.6342")
print(df.shape)
df[["id_cnj", "processo", "classe", "data_distribuicao", "orgao_julgador"]]

TRF3 cpopg:   0%|          | 0/1 [00:00<?, ?it/s]

TRF3 cpopg: 100%|██████████| 1/1 [00:04<00:00,  4.87s/it]

TRF3 cpopg: 100%|██████████| 1/1 [00:04<00:00,  4.87s/it]

(1, 14)

,id_cnj,processo,classe,data_distribuicao,orgao_julgador
0,50035362120254036342,5003536-21.2025.4.03.6342,PROCEDIMENTO DO JUIZADO ESPECIAL CÍVEL (436),24/09/2025,1ª Vara Gabinete JEF de Barueri

## Available columns

In [3]:
df.columns.tolist()

['id_cnj',
 'processo',
 'classe',
 'assunto',
 'data_distribuicao',
 'orgao_julgador',
 'orgao_julgador_colegiado',
 'jurisdicao',
 'endereco_orgao',
 'polo_ativo',
 'polo_passivo',
 'outros_interessados',
 'movimentacoes',
 'documentos']

The scalar columns come first; `polo_ativo`, `polo_passivo`,
`outros_interessados`, `movimentacoes` and `documentos` are lists of dicts.
Paginated sections (movements are served 15 per page) are fetched in full.

## Inspecting movements

In [4]:
movs = df.iloc[0]["movimentacoes"]
print(f"{len(movs)} events recorded")
for m in movs[:3]:
    print(f"  {m['data']} - {m['descricao']}")

70 events recorded
  24/09/2026 11:38:16 - Juntada de Petição de recurso inominado
  23/09/2026 13:25:54 - Juntada de Petição de ciência
  23/09/2026 10:23:38 - Expedição de Outros documentos.

## Inspecting parties

In [5]:
for polo in ["polo_ativo", "polo_passivo"]:
    print(polo)
    for p in df.iloc[0][polo]:
        print(f"  - {p['nome']} ({p['tipo']})")

polo_ativo
  - CINTIA REGIANE CORREA DOS SANTOS (AUTOR)
  - FERNANDO VANCETTI DA SILVA (ADVOGADO)
  - PAULO LEANDRO FAUSTINO (ADVOGADO)
polo_passivo
  - INSTITUTO NACIONAL DO SEGURO SOCIAL - INSS (REU)

## Appeals (`cposg`)

`cposg` takes the same arguments and returns the same columns, querying the
second-instance app. An appeal usually keeps the CNJ number of the original
case; `orgao_julgador_colegiado` carries the panel (turma).

In [6]:
df_2g = trf3.cposg("5021122-65.2018.4.03.6100")
df_2g[["id_cnj", "processo", "classe", "orgao_julgador", "orgao_julgador_colegiado"]]

TRF3 cposg:   0%|          | 0/1 [00:00<?, ?it/s]

TRF3 cposg: 100%|██████████| 1/1 [00:02<00:00,  2.92s/it]

TRF3 cposg: 100%|██████████| 1/1 [00:02<00:00,  2.92s/it]

,id_cnj,processo,classe,orgao_julgador,orgao_julgador_colegiado
0,50211226520184036100,5021122-65.2018.4.03.6100,APELAÇÃO CÍVEL (198),Gab. 13 - DES. FED. MONICA NOBRE,4ª Turma

## Handling processes the public portal cannot return

When a CNJ does not surface in the public consultation (sealed or simply not
found), the row carries only `id_cnj`, so callers can still distinguish
"looked up but missing" from "never tried".

In [7]:
df_missing = trf3.cpopg("00000000020994030000")
df_missing

TRF3 cpopg:   0%|          | 0/1 [00:00<?, ?it/s]

TRF3 cpopg: 100%|██████████| 1/1 [00:00<00:00, 17.88it/s]

                 id_cnj
0  00000000020994030000

## Downloading the documents

With `download_pecas=True`, each listed document is saved as a PDF under
`<diretorio>/<cnj>/<id>.pdf`, and the `pecas` column lists the paths.

In [8]:
import tempfile
from pathlib import Path

df_pecas = trf3.cpopg("5003536-21.2025.4.03.6342", download_pecas=True, diretorio=tempfile.mkdtemp())
for caminho in df_pecas.iloc[0]["pecas"]:
    print(Path(caminho).parent.name, Path(caminho).stat().st_size, "bytes")

TRF3 cpopg:   0%|          | 0/1 [00:00<?, ?it/s]

TRF3 cpopg: 100%|██████████| 1/1 [00:04<00:00,  4.84s/it]

TRF3 cpopg: 100%|██████████| 1/1 [00:04<00:00,  4.84s/it]

50035362120254036342 41357 bytes
50035362120254036342 5555 bytes
50035362120254036342 22494 bytes

## Splitting download from parse

`cpopg_download` returns, per CNJ, a dict with the raw JSON envelopes of each
API route (or `None` when the process was not found); `cpopg_parse` turns that
list into the DataFrame. Useful to cache the raw responses before processing.

In [9]:
brutos = trf3.cpopg_download("5003536-21.2025.4.03.6342")
print(sorted(brutos[0]))

df_again = trf3.cpopg_parse(brutos, ["50035362120254036342"])
df_again[["id_cnj", "processo", "data_distribuicao"]]

TRF3 cpopg:   0%|          | 0/1 [00:00<?, ?it/s]

TRF3 cpopg: 100%|██████████| 1/1 [00:12<00:00, 12.44s/it]

TRF3 cpopg: 100%|██████████| 1/1 [00:12<00:00, 12.44s/it]

['busca', 'dados', 'documentos', 'movimentacoes', 'outrosInteressados', 'poloAtivo', 'poloPassivo']

                 id_cnj                   processo data_distribuicao
0  50035362120254036342  5003536-21.2025.4.03.6342        24/09/2025